#define TInputOutputTree_cxx
#include "TInputOutputTree.h"
#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>

TInputOutputTree::TInputOutputTree()
{
   
}

TInputOutputTree::~TInputOutputTree()
{

}

void TInputOutputTree::InitInput(TTree *tree, bool isMC){
      //global event
  treeLeaf.run=0;
  treeLeaf.event=0;
  treeLeaf.lumis=0;
  treeLeaf.isData=0;
  treeLeaf.nVtx=0;
  treeLeaf.nTrksPV=0;
  treeLeaf.vtx=0;
  treeLeaf.vty=0;
  treeLeaf.vtz=0;
  treeLeaf.rho=0;
  treeLeaf.rhoCentral=0;
  treeLeaf.HLTEleMuX=0;
  treeLeaf.HLTPho=0;
  treeLeaf.HLTJet=0;
  treeLeaf.HLTEleMuXIsPrescaled=0;
  treeLeaf.HLTPhoIsPrescaled=0;
  treeLeaf.HLTJetIsPrescaled=0;
  if (isMC){
    treeLeaf.pdf = 0;
    treeLeaf.nPU = 0;
    treeLeaf.puBX = 0;
    treeLeaf.puTrue = 0;
    treeLeaf.mcPID = 0;
    treeLeaf.mcVtx = 0;
    treeLeaf.mcVty = 0;
    treeLeaf.mcVtz = 0;
    treeLeaf.mcPt = 0;
    treeLeaf.mcMass = 0;
    treeLeaf.mcEta = 0;
    treeLeaf.mcPhi = 0;
    treeLeaf.mcE = 0;
    treeLeaf.mcEt = 0;
    treeLeaf.mcGMomPID = 0;
    treeLeaf.mcMomPID = 0;
    treeLeaf.mcMomPt = 0;
    treeLeaf.mcMomMass = 0;
    treeLeaf.mcMomEta = 0;
    treeLeaf.mcMomPhi = 0;
    treeLeaf.mcIndex = 0;
    treeLeaf.mcStatusFlag = 0;
    treeLeaf.mcParentage = 0;
    treeLeaf.mcStatus = 0;
    treeLeaf.mcCalIsoDR03 = 0;
    treeLeaf.mcTrkIsoDR03 = 0;
    treeLeaf.mcCalIsoDR04 = 0;
    treeLeaf.mcTrkIsoDR04 = 0;
    treeLeaf.genMET = 0;
    treeLeaf.genMETPhi = 0;
  }
  treeLeaf.metFilters=0;
  treeLeaf.pfMET=0;
  treeLeaf.pfMETPhi=0;
  treeLeaf.pfMETsumEt=0;
  treeLeaf.pfMETmEtSig=0;
  treeLeaf.pfMETSig=0;
  treeLeaf.pfMET_T1JERUp=0;
  treeLeaf.pfMET_T1JERDo=0;
  treeLeaf.pfMET_T1JESUp=0;
  treeLeaf.pfMET_T1JESDo=0;
  treeLeaf.pfMET_T1MESUp=0;
  treeLeaf.pfMET_T1MESDo=0;
  treeLeaf.pfMET_T1EESUp=0;
  treeLeaf.pfMET_T1EESDo=0;
  treeLeaf.pfMET_T1PESUp=0;
  treeLeaf.pfMET_T1PESDo=0;
  treeLeaf.pfMET_T1TESUp=0;
  treeLeaf.pfMET_T1TESDo=0;
  treeLeaf.pfMET_T1UESUp=0;
  treeLeaf.pfMET_T1UESDo=0;
  treeLeaf.nPho=0;
  treeLeaf.phoE=0;
  treeLeaf.phoEt=0;
  treeLeaf.phoEta=0;
  treeLeaf.phoPhi=0;
  treeLeaf.phoSCE=0;
  treeLeaf.phoSCRawE=0;
  treeLeaf.phoESEn=0;
  treeLeaf.phoESEnP1=0;
  treeLeaf.phoESEnP2=0;
  treeLeaf.phoSCEta=0;
  treeLeaf.phoSCPhi=0;
  treeLeaf.phoSCEtaWidth=0;
  treeLeaf.phoSCPhiWidth=0;
  treeLeaf.phoSCBrem=0;
  treeLeaf.phohasPixelSeed=0;
  treeLeaf.phoEleVeto=0;
  treeLeaf.phoR9=0;
  treeLeaf.phoHoverE=0;
  treeLeaf.phoSigmaIEtaIEta=0;
  treeLeaf.phoSigmaIEtaIPhi=0;
  treeLeaf.phoSigmaIPhiIPhi=0;
  treeLeaf.phoE1x3=0;
  treeLeaf.phoE2x2=0;
  treeLeaf.phoE2x5Max=0;
  treeLeaf.phoE5x5=0;
  treeLeaf.phoESEffSigmaRR=0;
  treeLeaf.phoSigmaIEtaIEtaFull5x5=0;
  treeLeaf.phoSigmaIEtaIPhiFull5x5=0;
  treeLeaf.phoSigmaIPhiIPhiFull5x5=0;
  treeLeaf.phoE1x3Full5x5=0;
  treeLeaf.phoE2x2Full5x5=0;
  treeLeaf.phoE2x5MaxFull5x5=0;
  treeLeaf.phoE5x5Full5x5=0;
  treeLeaf.phoR9Full5x5=0;
  treeLeaf.phoSeedBCE=0;
  treeLeaf.phoSeedBCEta=0;
  treeLeaf.phoPFChIso=0;
  treeLeaf.phoPFPhoIso=0;
  treeLeaf.phoPFNeuIso=0;
  treeLeaf.phoPFChWorstIso=0;
  treeLeaf.phoPFChIsoFrix1=0;
  treeLeaf.phoPFChIsoFrix2=0;
  treeLeaf.phoPFChIsoFrix3=0;
  treeLeaf.phoPFChIsoFrix4=0;
  treeLeaf.phoPFChIsoFrix5=0;
  treeLeaf.phoPFChIsoFrix6=0;
  treeLeaf.phoPFChIsoFrix7=0;
  treeLeaf.phoPFChIsoFrix8=0;
  treeLeaf.phoPFPhoIsoFrix1=0;
  treeLeaf.phoPFPhoIsoFrix2=0;
  treeLeaf.phoPFPhoIsoFrix3=0;
  treeLeaf.phoPFPhoIsoFrix4=0;
  treeLeaf.phoPFPhoIsoFrix5=0;
  treeLeaf.phoPFPhoIsoFrix6=0;
  treeLeaf.phoPFPhoIsoFrix7=0;
  treeLeaf.phoPFPhoIsoFrix8=0;
  treeLeaf.phoPFNeuIsoFrix1=0;
  treeLeaf.phoPFNeuIsoFrix2=0;
  treeLeaf.phoPFNeuIsoFrix3=0;
  treeLeaf.phoPFNeuIsoFrix4=0;
  treeLeaf.phoPFNeuIsoFrix5=0;
  treeLeaf.phoPFNeuIsoFrix6=0;
  treeLeaf.phoPFNeuIsoFrix7=0;
  treeLeaf.phoPFNeuIsoFrix8=0;
  treeLeaf.phoEcalRecHitSumEtConeDR03=0;
  treeLeaf.phohcalDepth1TowerSumEtConeDR03=0;
  treeLeaf.phohcalDepth2TowerSumEtConeDR03=0;
  treeLeaf.phohcalTowerSumEtConeDR03=0;
  treeLeaf.photrkSumPtHollowConeDR03=0;
  treeLeaf.phoIDMVA=0;
  treeLeaf.phoFiredSingleTrgs=0;
  treeLeaf.phoFiredDoubleTrgs=0;
  treeLeaf.phoIDbit=0;
  treeLeaf.nEle=0;
  treeLeaf.eleCharge=0;
  treeLeaf.eleChargeConsistent=0;
  treeLeaf.eleEn=0;
  treeLeaf.eleSCEn=0;
  treeLeaf.eleESEn=0;
  treeLeaf.eleESEnP1=0;
  treeLeaf.eleESEnP2=0;
  treeLeaf.eleD0=0;
  treeLeaf.eleDz=0;
  treeLeaf.elePt=0;
  treeLeaf.eleEta=0;
  treeLeaf.elePhi=0;
  treeLeaf.eleR9=0;
  treeLeaf.eleSCEta=0;
  treeLeaf.eleSCPhi=0;
  treeLeaf.eleSCRawEn=0;
  treeLeaf.eleSCEtaWidth=0;
  treeLeaf.eleSCPhiWidth=0;
  treeLeaf.eleHoverE=0;
  treeLeaf.eleEoverP=0;
  treeLeaf.eleEoverPout=0;
  treeLeaf.eleEoverPInv=0;
  treeLeaf.eleBrem=0;
  treeLeaf.eledEtaAtVtx=0;
  treeLeaf.eledPhiAtVtx=0;
  treeLeaf.eledEtaAtCalo=0;
  treeLeaf.eleSigmaIEtaIEta=0;
  treeLeaf.eleSigmaIEtaIPhi=0;
  treeLeaf.eleSigmaIPhiIPhi=0;
  treeLeaf.eleSigmaIEtaIEtaFull5x5=0;
  treeLeaf.eleSigmaIPhiIPhiFull5x5=0;
  treeLeaf.eleConvVeto=0;
  treeLeaf.eleMissHits=0;
  treeLeaf.eleESEffSigmaRR=0;
  treeLeaf.elePFChIso=0;
  treeLeaf.elePFPhoIso=0;
  treeLeaf.elePFNeuIso=0;
  treeLeaf.elePFPUIso=0;
  treeLeaf.eleIDMVANonTrg=0;
  treeLeaf.eleIDMVATrg=0;
  treeLeaf.eledEtaseedAtVtx=0;
  treeLeaf.eleE1x5=0;
  treeLeaf.eleE2x5=0;
  treeLeaf.eleE5x5=0;
  treeLeaf.eleE1x5Full5x5=0;
  treeLeaf.eleE2x5Full5x5=0;
  treeLeaf.eleE5x5Full5x5=0;
  treeLeaf.eleR9Full5x5=0;
  treeLeaf.eleEcalDrivenSeed=0;
  treeLeaf.eleDr03EcalRecHitSumEt=0;
  treeLeaf.eleDr03HcalDepth1TowerSumEt=0;
  treeLeaf.eleDr03HcalDepth2TowerSumEt=0;
  treeLeaf.eleDr03HcalTowerSumEt=0;
  treeLeaf.eleDr03TkSumPt=0;
  treeLeaf.elecaloEnergy=0;
  treeLeaf.eleTrkdxy=0;
  treeLeaf.eleKFHits=0;
  treeLeaf.eleKFChi2=0;
  treeLeaf.eleGSFPt=0;
  treeLeaf.eleGSFEta=0;
  treeLeaf.eleGSFPhi=0;
  treeLeaf.eleGSFCharge=0;
  treeLeaf.eleGSFHits=0;
  treeLeaf.eleGSFMissHits=0;
  treeLeaf.eleGSFNHitsMax=0;
  treeLeaf.eleGSFVtxProb=0;
  treeLeaf.eleGSFlxyPV=0;
  treeLeaf.eleGSFlxyBS=0;
  treeLeaf.eleBCEn=0;
  treeLeaf.eleBCEta=0;
  treeLeaf.eleBCPhi=0;
  treeLeaf.eleBCS25=0;
  treeLeaf.eleBCS15=0;
  treeLeaf.eleBCSieie=0;
  treeLeaf.eleBCSieip=0;
  treeLeaf.eleBCSipip=0;
  treeLeaf.eleFiredTrgs=0;
  treeLeaf.eleIDbit=0;
  treeLeaf.eleESEnP1Raw=0;
  treeLeaf.eleESEnP2Raw=0;
  treeLeaf.nGSFTrk=0;
  treeLeaf.gsfPt=0;
  treeLeaf.gsfEta=0;
  treeLeaf.gsfPhi=0;
  treeLeaf.npfHF=0;
  treeLeaf.pfHFEn=0;
  treeLeaf.pfHFECALEn=0;
  treeLeaf.pfHFHCALEn=0;
  treeLeaf.pfHFPt=0;
  treeLeaf.pfHFEta=0;
  treeLeaf.pfHFPhi=0;
  treeLeaf.pfHFIso=0;
  treeLeaf.nMu=0;
  treeLeaf.muPt=0;
  treeLeaf.muEn=0;
  treeLeaf.muEta=0;
  treeLeaf.muPhi=0;
  treeLeaf.muCharge=0;
  treeLeaf.muType=0;
  treeLeaf.muIsLooseID=0;
  treeLeaf.muIsMediumID=0;
  treeLeaf.muIsTightID=0;
  treeLeaf.muIsSoftID=0;
  treeLeaf.muIsHighPtID=0;
  treeLeaf.muD0=0;
  treeLeaf.muDz=0;
  treeLeaf.muChi2NDF=0;
  treeLeaf.muInnerD0=0;
  treeLeaf.muInnerDz=0;
  treeLeaf.muTrkLayers=0;
  treeLeaf.muPixelLayers=0;
  treeLeaf.muPixelHits=0;
  treeLeaf.muMuonHits=0;
  treeLeaf.muStations=0;
  treeLeaf.muTrkQuality=0;
  treeLeaf.muIsoTrk=0;
  treeLeaf.muPFChIso=0;
  treeLeaf.muPFPhoIso=0;
  treeLeaf.muPFNeuIso=0;
  treeLeaf.muPFPUIso=0;
  treeLeaf.muFiredTrgs=0;
  treeLeaf.muInnervalidFraction=0;
  treeLeaf.musegmentCompatibility=0;
  treeLeaf.muchi2LocalPosition=0;
  treeLeaf.mutrkKink=0;
  treeLeaf.muBestTrkPtError=0;
  treeLeaf.muBestTrkPt=0;
  treeLeaf.nJet=0;
  treeLeaf.jetPt=0;
  treeLeaf.jetEn=0;
  treeLeaf.jetEta=0;
  treeLeaf.jetPhi=0;
  treeLeaf.jetRawPt=0;
  treeLeaf.jetRawEn=0;
  treeLeaf.jetArea=0;
  treeLeaf.jetpfCombinedInclusiveSecondaryVertexV2BJetTags=0;
  treeLeaf.jetJetProbabilityBJetTags=0;
  treeLeaf.jetpfCombinedMVABJetTags=0;
  treeLeaf.jetPFLooseId=0;
  treeLeaf.jetPUidFullDiscriminant=0;
  treeLeaf.jetJECUnc=0;
  treeLeaf.jetFiredTrgs=0;
  treeLeaf.jetCHF=0;
  treeLeaf.jetNHF=0;
  treeLeaf.jetCEF=0;
  treeLeaf.jetNEF=0;
  treeLeaf.jetNCH=0;
  treeLeaf.jetHFHAE=0;
  treeLeaf.jetHFEME=0;
  treeLeaf.jetNConstituents=0;
  if (isMC){
    treeLeaf.jetPartonID = 0;
    treeLeaf.jetGenJetIndex = 0;
    treeLeaf.jetGenJetEn = 0;
    treeLeaf.jetGenJetPt = 0;
    treeLeaf.jetGenJetEta = 0;
    treeLeaf.jetGenJetPhi = 0;
    treeLeaf.jetGenPartonID = 0;
    treeLeaf.jetGenEn = 0;
    treeLeaf.jetGenPt = 0;
    treeLeaf.jetGenEta = 0;
    treeLeaf.jetGenPhi = 0;
    treeLeaf.jetGenPartonMomID = 0;
  }
  treeLeaf.nAK8Jet=0;
  treeLeaf.AK8JetPt=0;
  treeLeaf.AK8JetEn=0;
  treeLeaf.AK8JetRawPt=0;
  treeLeaf.AK8JetRawEn=0;
  treeLeaf.AK8JetEta=0;
  treeLeaf.AK8JetPhi=0;
  treeLeaf.AK8JetMass=0;
  treeLeaf.AK8Jet_tau1=0;
  treeLeaf.AK8Jet_tau2=0;
  treeLeaf.AK8Jet_tau3=0;
  treeLeaf.AK8JetCHF=0;
  treeLeaf.AK8JetNHF=0;
  treeLeaf.AK8JetCEF=0;
  treeLeaf.AK8JetNEF=0;
  treeLeaf.AK8JetNCH=0;
  treeLeaf.AK8Jetnconstituents=0;
  treeLeaf.AK8JetPFLooseId=0;
  treeLeaf.AK8CHSSoftDropJetMass=0;
  treeLeaf.AK8JetpfBoostedDSVBTag=0;
  treeLeaf.AK8JetJECUnc=0;
  if (isMC){
    treeLeaf.AK8JetPartonID = 0;
    treeLeaf.AK8JetGenJetIndex = 0;
    treeLeaf.AK8JetGenJetEn = 0;
    treeLeaf.AK8JetGenJetPt = 0;
    treeLeaf.AK8JetGenJetEta = 0;
    treeLeaf.AK8JetGenJetPhi = 0;
    treeLeaf.AK8JetGenPartonID = 0;
    treeLeaf.AK8JetGenEn = 0;
    treeLeaf.AK8JetGenPt = 0;
    treeLeaf.AK8JetGenEta = 0;
    treeLeaf.AK8JetGenPhi = 0;
    treeLeaf.AK8JetGenPartonMomID = 0;
  }
  treeLeaf.nAK8softdropSubjet=0;
  treeLeaf.AK8softdropSubjetPt=0;
  treeLeaf.AK8softdropSubjetEta=0;
  treeLeaf.AK8softdropSubjetPhi=0;
  treeLeaf.AK8softdropSubjetMass=0;
  treeLeaf.AK8softdropSubjetE=0;
  treeLeaf.AK8softdropSubjetCharge=0;
  treeLeaf.AK8softdropSubjetFlavour=0;
  treeLeaf.AK8softdropSubjetCSV=0;
  
  if (!tree) return;
  fChain = tree;
  fCurrent = -1;
  fChain->SetMakeClass(1);
  //global event
  fChain->SetBranchAddress("run", &treeLeaf.run, &b_run);
  fChain->SetBranchAddress("event", &treeLeaf.event, &b_event);
  fChain->SetBranchAddress("lumis", &treeLeaf.lumis, &b_lumis);
  fChain->SetBranchAddress("isData", &treeLeaf.isData, &b_isData);
  fChain->SetBranchAddress("nVtx", &treeLeaf.nVtx, &b_nVtx);
  fChain->SetBranchAddress("nTrksPV", &treeLeaf.nTrksPV, &b_nTrksPV);
  fChain->SetBranchAddress("vtx", &treeLeaf.vtx, &b_vtx);
  fChain->SetBranchAddress("vty", &treeLeaf.vty, &b_vty);
  fChain->SetBranchAddress("vtz", &treeLeaf.vtz, &b_vtz);
  fChain->SetBranchAddress("rho", &treeLeaf.rho, &b_rho);
  fChain->SetBranchAddress("rhoCentral", &treeLeaf.rhoCentral, &b_rhoCentral);
  fChain->SetBranchAddress("HLTEleMuX", &treeLeaf.HLTEleMuX, &b_HLTEleMuX);
  fChain->SetBranchAddress("HLTPho", &treeLeaf.HLTPho, &b_HLTPho);
  fChain->SetBranchAddress("HLTJet", &treeLeaf.HLTJet, &b_HLTJet);
  fChain->SetBranchAddress("HLTEleMuXIsPrescaled", &treeLeaf.HLTEleMuXIsPrescaled, &b_HLTEleMuXIsPrescaled);
  fChain->SetBranchAddress("HLTPhoIsPrescaled", &treeLeaf.HLTPhoIsPrescaled, &b_HLTPhoIsPrescaled);
  fChain->SetBranchAddress("HLTJetIsPrescaled", &treeLeaf.HLTJetIsPrescaled, &b_HLTJetIsPrescaled);
  if (isMC){
   fChain->SetBranchAddress("pdf", &treeLeaf.pdf, &b_pdf);
   fChain->SetBranchAddress("pthat", &treeLeaf.pthat, &b_pthat);
   fChain->SetBranchAddress("processID", &treeLeaf.processID, &b_processID);
   fChain->SetBranchAddress("genWeight", &treeLeaf.genWeight, &b_genWeight);
   fChain->SetBranchAddress("nPUInfo", &treeLeaf.nPUInfo, &b_nPUInfo);
   fChain->SetBranchAddress("nPU", &treeLeaf.nPU, &b_nPU);
   fChain->SetBranchAddress("puBX", &treeLeaf.puBX, &b_puBX);
   fChain->SetBranchAddress("puTrue", &treeLeaf.puTrue, &b_puTrue);
   fChain->SetBranchAddress("nMC", &treeLeaf.nMC, &b_nMC);
   fChain->SetBranchAddress("mcPID", &treeLeaf.mcPID, &b_mcPID);
   fChain->SetBranchAddress("mcVtx", &treeLeaf.mcVtx, &b_mcVtx);
   fChain->SetBranchAddress("mcVty", &treeLeaf.mcVty, &b_mcVty);
   fChain->SetBranchAddress("mcVtz", &treeLeaf.mcVtz, &b_mcVtz);
   fChain->SetBranchAddress("mcPt", &treeLeaf.mcPt, &b_mcPt);
   fChain->SetBranchAddress("mcMass", &treeLeaf.mcMass, &b_mcMass);
   fChain->SetBranchAddress("mcEta", &treeLeaf.mcEta, &b_mcEta);
   fChain->SetBranchAddress("mcPhi", &treeLeaf.mcPhi, &b_mcPhi);
   fChain->SetBranchAddress("mcE", &treeLeaf.mcE, &b_mcE);
   fChain->SetBranchAddress("mcEt", &treeLeaf.mcEt, &b_mcEt);
   fChain->SetBranchAddress("mcGMomPID", &treeLeaf.mcGMomPID, &b_mcGMomPID);
   fChain->SetBranchAddress("mcMomPID", &treeLeaf.mcMomPID, &b_mcMomPID);
   fChain->SetBranchAddress("mcMomPt", &treeLeaf.mcMomPt, &b_mcMomPt);
   fChain->SetBranchAddress("mcMomMass", &treeLeaf.mcMomMass, &b_mcMomMass);
   fChain->SetBranchAddress("mcMomEta", &treeLeaf.mcMomEta, &b_mcMomEta);
   fChain->SetBranchAddress("mcMomPhi", &treeLeaf.mcMomPhi, &b_mcMomPhi);
   fChain->SetBranchAddress("mcIndex", &treeLeaf.mcIndex, &b_mcIndex);
   fChain->SetBranchAddress("mcStatusFlag", &treeLeaf.mcStatusFlag, &b_mcStatusFlag);
   fChain->SetBranchAddress("mcParentage", &treeLeaf.mcParentage, &b_mcParentage);
   fChain->SetBranchAddress("mcStatus", &treeLeaf.mcStatus, &b_mcStatus);
   fChain->SetBranchAddress("mcCalIsoDR03", &treeLeaf.mcCalIsoDR03, &b_mcCalIsoDR03);
   fChain->SetBranchAddress("mcTrkIsoDR03", &treeLeaf.mcTrkIsoDR03, &b_mcTrkIsoDR03);
   fChain->SetBranchAddress("mcCalIsoDR04", &treeLeaf.mcCalIsoDR04, &b_mcCalIsoDR04);
   fChain->SetBranchAddress("mcTrkIsoDR04", &treeLeaf.mcTrkIsoDR04, &b_mcTrkIsoDR04);
   fChain->SetBranchAddress("genMET", &treeLeaf.genMET, &b_genMET);
   fChain->SetBranchAddress("genMETPhi", &treeLeaf.genMETPhi, &b_genMETPhi);
  }
  fChain->SetBranchAddress("metFilters", &treeLeaf.metFilters, &b_metFilters);
  fChain->SetBranchAddress("pfMET", &treeLeaf.pfMET, &b_pfMET);
  fChain->SetBranchAddress("pfMETPhi", &treeLeaf.pfMETPhi, &b_pfMETPhi);
  fChain->SetBranchAddress("pfMETsumEt", &treeLeaf.pfMETsumEt, &b_pfMETsumEt);
  fChain->SetBranchAddress("pfMETmEtSig", &treeLeaf.pfMETmEtSig, &b_pfMETmEtSig);
  fChain->SetBranchAddress("pfMETSig", &treeLeaf.pfMETSig, &b_pfMETSig);
  fChain->SetBranchAddress("pfMET_T1JERUp", &treeLeaf.pfMET_T1JERUp, &b_pfMET_T1JERUp);
  fChain->SetBranchAddress("pfMET_T1JERDo", &treeLeaf.pfMET_T1JERDo, &b_pfMET_T1JERDo);
  fChain->SetBranchAddress("pfMET_T1JESUp", &treeLeaf.pfMET_T1JESUp, &b_pfMET_T1JESUp);
  fChain->SetBranchAddress("pfMET_T1JESDo", &treeLeaf.pfMET_T1JESDo, &b_pfMET_T1JESDo);
  fChain->SetBranchAddress("pfMET_T1MESUp", &treeLeaf.pfMET_T1MESUp, &b_pfMET_T1MESUp);
  fChain->SetBranchAddress("pfMET_T1MESDo", &treeLeaf.pfMET_T1MESDo, &b_pfMET_T1MESDo);
  fChain->SetBranchAddress("pfMET_T1EESUp", &treeLeaf.pfMET_T1EESUp, &b_pfMET_T1EESUp);
  fChain->SetBranchAddress("pfMET_T1EESDo", &treeLeaf.pfMET_T1EESDo, &b_pfMET_T1EESDo);
  fChain->SetBranchAddress("pfMET_T1PESUp", &treeLeaf.pfMET_T1PESUp, &b_pfMET_T1PESUp);
  fChain->SetBranchAddress("pfMET_T1PESDo", &treeLeaf.pfMET_T1PESDo, &b_pfMET_T1PESDo);
  fChain->SetBranchAddress("pfMET_T1TESUp", &treeLeaf.pfMET_T1TESUp, &b_pfMET_T1TESUp);
  fChain->SetBranchAddress("pfMET_T1TESDo", &treeLeaf.pfMET_T1TESDo, &b_pfMET_T1TESDo);
  fChain->SetBranchAddress("pfMET_T1UESUp", &treeLeaf.pfMET_T1UESUp, &b_pfMET_T1UESUp);
  fChain->SetBranchAddress("pfMET_T1UESDo", &treeLeaf.pfMET_T1UESDo, &b_pfMET_T1UESDo);
  fChain->SetBranchAddress("nPho", &treeLeaf.nPho, &b_nPho);
  fChain->SetBranchAddress("phoE", &treeLeaf.phoE, &b_phoE);
  fChain->SetBranchAddress("phoEt", &treeLeaf.phoEt, &b_phoEt);
  fChain->SetBranchAddress("phoEta", &treeLeaf.phoEta, &b_phoEta);
  fChain->SetBranchAddress("phoPhi", &treeLeaf.phoPhi, &b_phoPhi);
  fChain->SetBranchAddress("phoSCE", &treeLeaf.phoSCE, &b_phoSCE);
  fChain->SetBranchAddress("phoSCRawE", &treeLeaf.phoSCRawE, &b_phoSCRawE);
  fChain->SetBranchAddress("phoESEn", &treeLeaf.phoESEn, &b_phoESEn);
  fChain->SetBranchAddress("phoESEnP1", &treeLeaf.phoESEnP1, &b_phoESEnP1);
  fChain->SetBranchAddress("phoESEnP2", &treeLeaf.phoESEnP2, &b_phoESEnP2);
  fChain->SetBranchAddress("phoSCEta", &treeLeaf.phoSCEta, &b_phoSCEta);
  fChain->SetBranchAddress("phoSCPhi", &treeLeaf.phoSCPhi, &b_phoSCPhi);
  fChain->SetBranchAddress("phoSCEtaWidth", &treeLeaf.phoSCEtaWidth, &b_phoSCEtaWidth);
  fChain->SetBranchAddress("phoSCPhiWidth", &treeLeaf.phoSCPhiWidth, &b_phoSCPhiWidth);
  fChain->SetBranchAddress("phoSCBrem", &treeLeaf.phoSCBrem, &b_phoSCBrem);
  fChain->SetBranchAddress("phohasPixelSeed", &treeLeaf.phohasPixelSeed, &b_phohasPixelSeed);
  fChain->SetBranchAddress("phoEleVeto", &treeLeaf.phoEleVeto, &b_phoEleVeto);
  fChain->SetBranchAddress("phoR9", &treeLeaf.phoR9, &b_phoR9);
  fChain->SetBranchAddress("phoHoverE", &treeLeaf.phoHoverE, &b_phoHoverE);
  fChain->SetBranchAddress("phoSigmaIEtaIEta", &treeLeaf.phoSigmaIEtaIEta, &b_phoSigmaIEtaIEta);
  fChain->SetBranchAddress("phoSigmaIEtaIPhi", &treeLeaf.phoSigmaIEtaIPhi, &b_phoSigmaIEtaIPhi);
  fChain->SetBranchAddress("phoSigmaIPhiIPhi", &treeLeaf.phoSigmaIPhiIPhi, &b_phoSigmaIPhiIPhi);
  fChain->SetBranchAddress("phoE1x3", &treeLeaf.phoE1x3, &b_phoE1x3);
  fChain->SetBranchAddress("phoE2x2", &treeLeaf.phoE2x2, &b_phoE2x2);
  fChain->SetBranchAddress("phoE2x5Max", &treeLeaf.phoE2x5Max, &b_phoE2x5Max);
  fChain->SetBranchAddress("phoE5x5", &treeLeaf.phoE5x5, &b_phoE5x5);
  fChain->SetBranchAddress("phoESEffSigmaRR", &treeLeaf.phoESEffSigmaRR, &b_phoESEffSigmaRR);
  fChain->SetBranchAddress("phoSigmaIEtaIEtaFull5x5", &treeLeaf.phoSigmaIEtaIEtaFull5x5, &b_phoSigmaIEtaIEtaFull5x5);
  fChain->SetBranchAddress("phoSigmaIEtaIPhiFull5x5", &treeLeaf.phoSigmaIEtaIPhiFull5x5, &b_phoSigmaIEtaIPhiFull5x5);
  fChain->SetBranchAddress("phoSigmaIPhiIPhiFull5x5", &treeLeaf.phoSigmaIPhiIPhiFull5x5, &b_phoSigmaIPhiIPhiFull5x5);
  fChain->SetBranchAddress("phoE1x3Full5x5", &treeLeaf.phoE1x3Full5x5, &b_phoE1x3Full5x5);
  fChain->SetBranchAddress("phoE2x2Full5x5", &treeLeaf.phoE2x2Full5x5, &b_phoE2x2Full5x5);
  fChain->SetBranchAddress("phoE2x5MaxFull5x5", &treeLeaf.phoE2x5MaxFull5x5, &b_phoE2x5MaxFull5x5);
  fChain->SetBranchAddress("phoE5x5Full5x5", &treeLeaf.phoE5x5Full5x5, &b_phoE5x5Full5x5);
  fChain->SetBranchAddress("phoR9Full5x5", &treeLeaf.phoR9Full5x5, &b_phoR9Full5x5);
  fChain->SetBranchAddress("phoSeedBCE", &treeLeaf.phoSeedBCE, &b_phoSeedBCE);
  fChain->SetBranchAddress("phoSeedBCEta", &treeLeaf.phoSeedBCEta, &b_phoSeedBCEta);
  fChain->SetBranchAddress("phoPFChIso", &treeLeaf.phoPFChIso, &b_phoPFChIso);
  fChain->SetBranchAddress("phoPFPhoIso", &treeLeaf.phoPFPhoIso, &b_phoPFPhoIso);
  fChain->SetBranchAddress("phoPFNeuIso", &treeLeaf.phoPFNeuIso, &b_phoPFNeuIso);
  fChain->SetBranchAddress("phoPFChWorstIso", &treeLeaf.phoPFChWorstIso, &b_phoPFChWorstIso);
  fChain->SetBranchAddress("phoPFChIsoFrix1", &treeLeaf.phoPFChIsoFrix1, &b_phoPFChIsoFrix1);
  fChain->SetBranchAddress("phoPFChIsoFrix2", &treeLeaf.phoPFChIsoFrix2, &b_phoPFChIsoFrix2);
  fChain->SetBranchAddress("phoPFChIsoFrix3", &treeLeaf.phoPFChIsoFrix3, &b_phoPFChIsoFrix3);
  fChain->SetBranchAddress("phoPFChIsoFrix4", &treeLeaf.phoPFChIsoFrix4, &b_phoPFChIsoFrix4);
  fChain->SetBranchAddress("phoPFChIsoFrix5", &treeLeaf.phoPFChIsoFrix5, &b_phoPFChIsoFrix5);
  fChain->SetBranchAddress("phoPFChIsoFrix6", &treeLeaf.phoPFChIsoFrix6, &b_phoPFChIsoFrix6);
  fChain->SetBranchAddress("phoPFChIsoFrix7", &treeLeaf.phoPFChIsoFrix7, &b_phoPFChIsoFrix7);
  fChain->SetBranchAddress("phoPFChIsoFrix8", &treeLeaf.phoPFChIsoFrix8, &b_phoPFChIsoFrix8);
  fChain->SetBranchAddress("phoPFPhoIsoFrix1", &treeLeaf.phoPFPhoIsoFrix1, &b_phoPFPhoIsoFrix1);
  fChain->SetBranchAddress("phoPFPhoIsoFrix2", &treeLeaf.phoPFPhoIsoFrix2, &b_phoPFPhoIsoFrix2);
  fChain->SetBranchAddress("phoPFPhoIsoFrix3", &treeLeaf.phoPFPhoIsoFrix3, &b_phoPFPhoIsoFrix3);
  fChain->SetBranchAddress("phoPFPhoIsoFrix4", &treeLeaf.phoPFPhoIsoFrix4, &b_phoPFPhoIsoFrix4);
  fChain->SetBranchAddress("phoPFPhoIsoFrix5", &treeLeaf.phoPFPhoIsoFrix5, &b_phoPFPhoIsoFrix5);
  fChain->SetBranchAddress("phoPFPhoIsoFrix6", &treeLeaf.phoPFPhoIsoFrix6, &b_phoPFPhoIsoFrix6);
  fChain->SetBranchAddress("phoPFPhoIsoFrix7", &treeLeaf.phoPFPhoIsoFrix7, &b_phoPFPhoIsoFrix7);
  fChain->SetBranchAddress("phoPFPhoIsoFrix8", &treeLeaf.phoPFPhoIsoFrix8, &b_phoPFPhoIsoFrix8);
  fChain->SetBranchAddress("phoPFNeuIsoFrix1", &treeLeaf.phoPFNeuIsoFrix1, &b_phoPFNeuIsoFrix1);
  fChain->SetBranchAddress("phoPFNeuIsoFrix2", &treeLeaf.phoPFNeuIsoFrix2, &b_phoPFNeuIsoFrix2);
  fChain->SetBranchAddress("phoPFNeuIsoFrix3", &treeLeaf.phoPFNeuIsoFrix3, &b_phoPFNeuIsoFrix3);
  fChain->SetBranchAddress("phoPFNeuIsoFrix4", &treeLeaf.phoPFNeuIsoFrix4, &b_phoPFNeuIsoFrix4);
  fChain->SetBranchAddress("phoPFNeuIsoFrix5", &treeLeaf.phoPFNeuIsoFrix5, &b_phoPFNeuIsoFrix5);
  fChain->SetBranchAddress("phoPFNeuIsoFrix6", &treeLeaf.phoPFNeuIsoFrix6, &b_phoPFNeuIsoFrix6);
  fChain->SetBranchAddress("phoPFNeuIsoFrix7", &treeLeaf.phoPFNeuIsoFrix7, &b_phoPFNeuIsoFrix7);
  fChain->SetBranchAddress("phoPFNeuIsoFrix8", &treeLeaf.phoPFNeuIsoFrix8, &b_phoPFNeuIsoFrix8);
  fChain->SetBranchAddress("phoEcalRecHitSumEtConeDR03", &treeLeaf.phoEcalRecHitSumEtConeDR03, &b_phoEcalRecHitSumEtConeDR03);
  fChain->SetBranchAddress("phohcalDepth1TowerSumEtConeDR03", &treeLeaf.phohcalDepth1TowerSumEtConeDR03, &b_phohcalDepth1TowerSumEtConeDR03);
  fChain->SetBranchAddress("phohcalDepth2TowerSumEtConeDR03", &treeLeaf.phohcalDepth2TowerSumEtConeDR03, &b_phohcalDepth2TowerSumEtConeDR03);
  fChain->SetBranchAddress("phohcalTowerSumEtConeDR03", &treeLeaf.phohcalTowerSumEtConeDR03, &b_phohcalTowerSumEtConeDR03);
  fChain->SetBranchAddress("photrkSumPtHollowConeDR03", &treeLeaf.photrkSumPtHollowConeDR03, &b_photrkSumPtHollowConeDR03);
  fChain->SetBranchAddress("phoIDMVA", &treeLeaf.phoIDMVA, &b_phoIDMVA);
  fChain->SetBranchAddress("phoFiredSingleTrgs", &treeLeaf.phoFiredSingleTrgs, &b_phoFiredSingleTrgs);
  fChain->SetBranchAddress("phoFiredDoubleTrgs", &treeLeaf.phoFiredDoubleTrgs, &b_phoFiredDoubleTrgs);
  fChain->SetBranchAddress("phoIDbit", &treeLeaf.phoIDbit, &b_phoIDbit);
  fChain->SetBranchAddress("nEle", &treeLeaf.nEle, &b_nEle);
  fChain->SetBranchAddress("eleCharge", &treeLeaf.eleCharge, &b_eleCharge);
  fChain->SetBranchAddress("eleChargeConsistent", &treeLeaf.eleChargeConsistent, &b_eleChargeConsistent);
  fChain->SetBranchAddress("eleEn", &treeLeaf.eleEn, &b_eleEn);
  fChain->SetBranchAddress("eleSCEn", &treeLeaf.eleSCEn, &b_eleSCEn);
  fChain->SetBranchAddress("eleESEn", &treeLeaf.eleESEn, &b_eleESEn);
  fChain->SetBranchAddress("eleESEnP1", &treeLeaf.eleESEnP1, &b_eleESEnP1);
  fChain->SetBranchAddress("eleESEnP2", &treeLeaf.eleESEnP2, &b_eleESEnP2);
  fChain->SetBranchAddress("eleD0", &treeLeaf.eleD0, &b_eleD0);
  fChain->SetBranchAddress("eleDz", &treeLeaf.eleDz, &b_eleDz);
  fChain->SetBranchAddress("elePt", &treeLeaf.elePt, &b_elePt);
  fChain->SetBranchAddress("eleEta", &treeLeaf.eleEta, &b_eleEta);
  fChain->SetBranchAddress("elePhi", &treeLeaf.elePhi, &b_elePhi);
  fChain->SetBranchAddress("eleR9", &treeLeaf.eleR9, &b_eleR9);
  fChain->SetBranchAddress("eleSCEta", &treeLeaf.eleSCEta, &b_eleSCEta);
  fChain->SetBranchAddress("eleSCPhi", &treeLeaf.eleSCPhi, &b_eleSCPhi);
  fChain->SetBranchAddress("eleSCRawEn", &treeLeaf.eleSCRawEn, &b_eleSCRawEn);
  fChain->SetBranchAddress("eleSCEtaWidth", &treeLeaf.eleSCEtaWidth, &b_eleSCEtaWidth);
  fChain->SetBranchAddress("eleSCPhiWidth", &treeLeaf.eleSCPhiWidth, &b_eleSCPhiWidth);
  fChain->SetBranchAddress("eleHoverE", &treeLeaf.eleHoverE, &b_eleHoverE);
  fChain->SetBranchAddress("eleEoverP", &treeLeaf.eleEoverP, &b_eleEoverP);
  fChain->SetBranchAddress("eleEoverPout", &treeLeaf.eleEoverPout, &b_eleEoverPout);
  fChain->SetBranchAddress("eleEoverPInv", &treeLeaf.eleEoverPInv, &b_eleEoverPInv);
  fChain->SetBranchAddress("eleBrem", &treeLeaf.eleBrem, &b_eleBrem);
  fChain->SetBranchAddress("eledEtaAtVtx", &treeLeaf.eledEtaAtVtx, &b_eledEtaAtVtx);
  fChain->SetBranchAddress("eledPhiAtVtx", &treeLeaf.eledPhiAtVtx, &b_eledPhiAtVtx);
  fChain->SetBranchAddress("eledEtaAtCalo", &treeLeaf.eledEtaAtCalo, &b_eledEtaAtCalo);
  fChain->SetBranchAddress("eleSigmaIEtaIEta", &treeLeaf.eleSigmaIEtaIEta, &b_eleSigmaIEtaIEta);
  fChain->SetBranchAddress("eleSigmaIEtaIPhi", &treeLeaf.eleSigmaIEtaIPhi, &b_eleSigmaIEtaIPhi);
  fChain->SetBranchAddress("eleSigmaIPhiIPhi", &treeLeaf.eleSigmaIPhiIPhi, &b_eleSigmaIPhiIPhi);
  fChain->SetBranchAddress("eleSigmaIEtaIEtaFull5x5", &treeLeaf.eleSigmaIEtaIEtaFull5x5, &b_eleSigmaIEtaIEtaFull5x5);
  fChain->SetBranchAddress("eleSigmaIPhiIPhiFull5x5", &treeLeaf.eleSigmaIPhiIPhiFull5x5, &b_eleSigmaIPhiIPhiFull5x5);
  fChain->SetBranchAddress("eleConvVeto", &treeLeaf.eleConvVeto, &b_eleConvVeto);
  fChain->SetBranchAddress("eleMissHits", &treeLeaf.eleMissHits, &b_eleMissHits);
  fChain->SetBranchAddress("eleESEffSigmaRR", &treeLeaf.eleESEffSigmaRR, &b_eleESEffSigmaRR);
  fChain->SetBranchAddress("elePFChIso", &treeLeaf.elePFChIso, &b_elePFChIso);
  fChain->SetBranchAddress("elePFPhoIso", &treeLeaf.elePFPhoIso, &b_elePFPhoIso);
  fChain->SetBranchAddress("elePFNeuIso", &treeLeaf.elePFNeuIso, &b_elePFNeuIso);
  fChain->SetBranchAddress("elePFPUIso", &treeLeaf.elePFPUIso, &b_elePFPUIso);
  fChain->SetBranchAddress("eleIDMVANonTrg", &treeLeaf.eleIDMVANonTrg, &b_eleIDMVANonTrg);
  fChain->SetBranchAddress("eleIDMVATrg", &treeLeaf.eleIDMVATrg, &b_eleIDMVATrg);
  fChain->SetBranchAddress("eledEtaseedAtVtx", &treeLeaf.eledEtaseedAtVtx, &b_eledEtaseedAtVtx);
  fChain->SetBranchAddress("eleE1x5", &treeLeaf.eleE1x5, &b_eleE1x5);
  fChain->SetBranchAddress("eleE2x5", &treeLeaf.eleE2x5, &b_eleE2x5);
  fChain->SetBranchAddress("eleE5x5", &treeLeaf.eleE5x5, &b_eleE5x5);
  fChain->SetBranchAddress("eleE1x5Full5x5", &treeLeaf.eleE1x5Full5x5, &b_eleE1x5Full5x5);
  fChain->SetBranchAddress("eleE2x5Full5x5", &treeLeaf.eleE2x5Full5x5, &b_eleE2x5Full5x5);
  fChain->SetBranchAddress("eleE5x5Full5x5", &treeLeaf.eleE5x5Full5x5, &b_eleE5x5Full5x5);
  fChain->SetBranchAddress("eleR9Full5x5", &treeLeaf.eleR9Full5x5, &b_eleR9Full5x5);
  fChain->SetBranchAddress("eleEcalDrivenSeed", &treeLeaf.eleEcalDrivenSeed, &b_eleEcalDrivenSeed);
  fChain->SetBranchAddress("eleDr03EcalRecHitSumEt", &treeLeaf.eleDr03EcalRecHitSumEt, &b_eleDr03EcalRecHitSumEt);
  fChain->SetBranchAddress("eleDr03HcalDepth1TowerSumEt", &treeLeaf.eleDr03HcalDepth1TowerSumEt, &b_eleDr03HcalDepth1TowerSumEt);
  fChain->SetBranchAddress("eleDr03HcalDepth2TowerSumEt", &treeLeaf.eleDr03HcalDepth2TowerSumEt, &b_eleDr03HcalDepth2TowerSumEt);
  fChain->SetBranchAddress("eleDr03HcalTowerSumEt", &treeLeaf.eleDr03HcalTowerSumEt, &b_eleDr03HcalTowerSumEt);
  fChain->SetBranchAddress("eleDr03TkSumPt", &treeLeaf.eleDr03TkSumPt, &b_eleDr03TkSumPt);
  fChain->SetBranchAddress("elecaloEnergy", &treeLeaf.elecaloEnergy, &b_elecaloEnergy);
  fChain->SetBranchAddress("eleTrkdxy", &treeLeaf.eleTrkdxy, &b_eleTrkdxy);
  fChain->SetBranchAddress("eleKFHits", &treeLeaf.eleKFHits, &b_eleKFHits);
  fChain->SetBranchAddress("eleKFChi2", &treeLeaf.eleKFChi2, &b_eleKFChi2);
  fChain->SetBranchAddress("eleGSFPt", &treeLeaf.eleGSFPt, &b_eleGSFPt);
  fChain->SetBranchAddress("eleGSFEta", &treeLeaf.eleGSFEta, &b_eleGSFEta);
  fChain->SetBranchAddress("eleGSFPhi", &treeLeaf.eleGSFPhi, &b_eleGSFPhi);
  fChain->SetBranchAddress("eleGSFCharge", &treeLeaf.eleGSFCharge, &b_eleGSFCharge);
  fChain->SetBranchAddress("eleGSFHits", &treeLeaf.eleGSFHits, &b_eleGSFHits);
  fChain->SetBranchAddress("eleGSFMissHits", &treeLeaf.eleGSFMissHits, &b_eleGSFMissHits);
  fChain->SetBranchAddress("eleGSFNHitsMax", &treeLeaf.eleGSFNHitsMax, &b_eleGSFNHitsMax);
  fChain->SetBranchAddress("eleGSFVtxProb", &treeLeaf.eleGSFVtxProb, &b_eleGSFVtxProb);
  fChain->SetBranchAddress("eleGSFlxyPV", &treeLeaf.eleGSFlxyPV, &b_eleGSFlxyPV);
  fChain->SetBranchAddress("eleGSFlxyBS", &treeLeaf.eleGSFlxyBS, &b_eleGSFlxyBS);
  fChain->SetBranchAddress("eleBCEn", &treeLeaf.eleBCEn, &b_eleBCEn);
  fChain->SetBranchAddress("eleBCEta", &treeLeaf.eleBCEta, &b_eleBCEta);
  fChain->SetBranchAddress("eleBCPhi", &treeLeaf.eleBCPhi, &b_eleBCPhi);
  fChain->SetBranchAddress("eleBCS25", &treeLeaf.eleBCS25, &b_eleBCS25);
  fChain->SetBranchAddress("eleBCS15", &treeLeaf.eleBCS15, &b_eleBCS15);
  fChain->SetBranchAddress("eleBCSieie", &treeLeaf.eleBCSieie, &b_eleBCSieie);
  fChain->SetBranchAddress("eleBCSieip", &treeLeaf.eleBCSieip, &b_eleBCSieip);
  fChain->SetBranchAddress("eleBCSipip", &treeLeaf.eleBCSipip, &b_eleBCSipip);
  fChain->SetBranchAddress("eleFiredTrgs", &treeLeaf.eleFiredTrgs, &b_eleFiredTrgs);
  fChain->SetBranchAddress("eleIDbit", &treeLeaf.eleIDbit, &b_eleIDbit);
  fChain->SetBranchAddress("eleESEnP1Raw", &treeLeaf.eleESEnP1Raw, &b_eleESEnP1Raw);
  fChain->SetBranchAddress("eleESEnP2Raw", &treeLeaf.eleESEnP2Raw, &b_eleESEnP2Raw);
  fChain->SetBranchAddress("nGSFTrk", &treeLeaf.nGSFTrk, &b_nGSFTrk);
  fChain->SetBranchAddress("gsfPt", &treeLeaf.gsfPt, &b_gsfPt);
  fChain->SetBranchAddress("gsfEta", &treeLeaf.gsfEta, &b_gsfEta);
  fChain->SetBranchAddress("gsfPhi", &treeLeaf.gsfPhi, &b_gsfPhi);
  fChain->SetBranchAddress("npfHF", &treeLeaf.npfHF, &b_npfHF);
  fChain->SetBranchAddress("pfHFEn", &treeLeaf.pfHFEn, &b_pfHFEn);
  fChain->SetBranchAddress("pfHFECALEn", &treeLeaf.pfHFECALEn, &b_pfHFECALEn);
  fChain->SetBranchAddress("pfHFHCALEn", &treeLeaf.pfHFHCALEn, &b_pfHFHCALEn);
  fChain->SetBranchAddress("pfHFPt", &treeLeaf.pfHFPt, &b_pfHFPt);
  fChain->SetBranchAddress("pfHFEta", &treeLeaf.pfHFEta, &b_pfHFEta);
  fChain->SetBranchAddress("pfHFPhi", &treeLeaf.pfHFPhi, &b_pfHFPhi);
  fChain->SetBranchAddress("pfHFIso", &treeLeaf.pfHFIso, &b_pfHFIso);
  fChain->SetBranchAddress("nMu", &treeLeaf.nMu, &b_nMu);
  fChain->SetBranchAddress("muPt", &treeLeaf.muPt, &b_muPt);
  fChain->SetBranchAddress("muEn", &treeLeaf.muEn, &b_muEn);
  fChain->SetBranchAddress("muEta", &treeLeaf.muEta, &b_muEta);
  fChain->SetBranchAddress("muPhi", &treeLeaf.muPhi, &b_muPhi);
  fChain->SetBranchAddress("muCharge", &treeLeaf.muCharge, &b_muCharge);
  fChain->SetBranchAddress("muType", &treeLeaf.muType, &b_muType);
  fChain->SetBranchAddress("muIsLooseID", &treeLeaf.muIsLooseID, &b_muIsLooseID);
  fChain->SetBranchAddress("muIsMediumID", &treeLeaf.muIsMediumID, &b_muIsMediumID);
  fChain->SetBranchAddress("muIsTightID", &treeLeaf.muIsTightID, &b_muIsTightID);
  fChain->SetBranchAddress("muIsSoftID", &treeLeaf.muIsSoftID, &b_muIsSoftID);
  fChain->SetBranchAddress("muIsHighPtID", &treeLeaf.muIsHighPtID, &b_muIsHighPtID);
  fChain->SetBranchAddress("muD0", &treeLeaf.muD0, &b_muD0);
  fChain->SetBranchAddress("muDz", &treeLeaf.muDz, &b_muDz);
  fChain->SetBranchAddress("muChi2NDF", &treeLeaf.muChi2NDF, &b_muChi2NDF);
  fChain->SetBranchAddress("muInnerD0", &treeLeaf.muInnerD0, &b_muInnerD0);
  fChain->SetBranchAddress("muInnerDz", &treeLeaf.muInnerDz, &b_muInnerDz);
  fChain->SetBranchAddress("muTrkLayers", &treeLeaf.muTrkLayers, &b_muTrkLayers);
  fChain->SetBranchAddress("muPixelLayers", &treeLeaf.muPixelLayers, &b_muPixelLayers);
  fChain->SetBranchAddress("muPixelHits", &treeLeaf.muPixelHits, &b_muPixelHits);
  fChain->SetBranchAddress("muMuonHits", &treeLeaf.muMuonHits, &b_muMuonHits);
  fChain->SetBranchAddress("muStations", &treeLeaf.muStations, &b_muStations);
  fChain->SetBranchAddress("muTrkQuality", &treeLeaf.muTrkQuality, &b_muTrkQuality);
  fChain->SetBranchAddress("muIsoTrk", &treeLeaf.muIsoTrk, &b_muIsoTrk);
  fChain->SetBranchAddress("muPFChIso", &treeLeaf.muPFChIso, &b_muPFChIso);
  fChain->SetBranchAddress("muPFPhoIso", &treeLeaf.muPFPhoIso, &b_muPFPhoIso);
  fChain->SetBranchAddress("muPFNeuIso", &treeLeaf.muPFNeuIso, &b_muPFNeuIso);
  fChain->SetBranchAddress("muPFPUIso", &treeLeaf.muPFPUIso, &b_muPFPUIso);
  fChain->SetBranchAddress("muFiredTrgs", &treeLeaf.muFiredTrgs, &b_muFiredTrgs);
  fChain->SetBranchAddress("muInnervalidFraction", &treeLeaf.muInnervalidFraction, &b_muInnervalidFraction);
  fChain->SetBranchAddress("musegmentCompatibility", &treeLeaf.musegmentCompatibility, &b_musegmentCompatibility);
  fChain->SetBranchAddress("muchi2LocalPosition", &treeLeaf.muchi2LocalPosition, &b_muchi2LocalPosition);
  fChain->SetBranchAddress("mutrkKink", &treeLeaf.mutrkKink, &b_mutrkKink);
  fChain->SetBranchAddress("muBestTrkPtError", &treeLeaf.muBestTrkPtError, &b_muBestTrkPtError);
  fChain->SetBranchAddress("muBestTrkPt", &treeLeaf.muBestTrkPt, &b_muBestTrkPt);
  fChain->SetBranchAddress("nJet", &treeLeaf.nJet, &b_nJet);
  fChain->SetBranchAddress("jetPt", &treeLeaf.jetPt, &b_jetPt);
  fChain->SetBranchAddress("jetEn", &treeLeaf.jetEn, &b_jetEn);
  fChain->SetBranchAddress("jetEta", &treeLeaf.jetEta, &b_jetEta);
  fChain->SetBranchAddress("jetPhi", &treeLeaf.jetPhi, &b_jetPhi);
  fChain->SetBranchAddress("jetRawPt", &treeLeaf.jetRawPt, &b_jetRawPt);
  fChain->SetBranchAddress("jetRawEn", &treeLeaf.jetRawEn, &b_jetRawEn);
  fChain->SetBranchAddress("jetArea", &treeLeaf.jetArea, &b_jetArea);
  fChain->SetBranchAddress("jetpfCombinedInclusiveSecondaryVertexV2BJetTags", &treeLeaf.jetpfCombinedInclusiveSecondaryVertexV2BJetTags, &b_jetpfCombinedInclusiveSecondaryVertexV2BJetTags);
  fChain->SetBranchAddress("jetJetProbabilityBJetTags", &treeLeaf.jetJetProbabilityBJetTags, &b_jetJetProbabilityBJetTags);
  fChain->SetBranchAddress("jetpfCombinedMVABJetTags", &treeLeaf.jetpfCombinedMVABJetTags, &b_jetpfCombinedMVABJetTags);
  fChain->SetBranchAddress("jetPFLooseId", &treeLeaf.jetPFLooseId, &b_jetPFLooseId);
  fChain->SetBranchAddress("jetPUidFullDiscriminant", &treeLeaf.jetPUidFullDiscriminant, &b_jetPUidFullDiscriminant);
  fChain->SetBranchAddress("jetJECUnc", &treeLeaf.jetJECUnc, &b_jetJECUnc);
  fChain->SetBranchAddress("jetFiredTrgs", &treeLeaf.jetFiredTrgs, &b_jetFiredTrgs);
  fChain->SetBranchAddress("jetCHF", &treeLeaf.jetCHF, &b_jetCHF);
  fChain->SetBranchAddress("jetNHF", &treeLeaf.jetNHF, &b_jetNHF);
  fChain->SetBranchAddress("jetCEF", &treeLeaf.jetCEF, &b_jetCEF);
  fChain->SetBranchAddress("jetNEF", &treeLeaf.jetNEF, &b_jetNEF);
  fChain->SetBranchAddress("jetNCH", &treeLeaf.jetNCH, &b_jetNCH);
  fChain->SetBranchAddress("jetHFHAE", &treeLeaf.jetHFHAE, &b_jetHFHAE);
  fChain->SetBranchAddress("jetHFEME", &treeLeaf.jetHFEME, &b_jetHFEME);
  fChain->SetBranchAddress("jetNConstituents", &treeLeaf.jetNConstituents, &b_jetNConstituents);
  if (isMC){
   fChain->SetBranchAddress("jetPartonID", &treeLeaf.jetPartonID, &b_jetPartonID);
   fChain->SetBranchAddress("jetGenJetIndex", &treeLeaf.jetGenJetIndex, &b_jetGenJetIndex);
   fChain->SetBranchAddress("jetGenJetEn", &treeLeaf.jetGenJetEn, &b_jetGenJetEn);
   fChain->SetBranchAddress("jetGenJetPt", &treeLeaf.jetGenJetPt, &b_jetGenJetPt);
   fChain->SetBranchAddress("jetGenJetEta", &treeLeaf.jetGenJetEta, &b_jetGenJetEta);
   fChain->SetBranchAddress("jetGenJetPhi", &treeLeaf.jetGenJetPhi, &b_jetGenJetPhi);
   fChain->SetBranchAddress("jetGenPartonID", &treeLeaf.jetGenPartonID, &b_jetGenPartonID);
   fChain->SetBranchAddress("jetGenEn", &treeLeaf.jetGenEn, &b_jetGenEn);
   fChain->SetBranchAddress("jetGenPt", &treeLeaf.jetGenPt, &b_jetGenPt);
   fChain->SetBranchAddress("jetGenEta", &treeLeaf.jetGenEta, &b_jetGenEta);
   fChain->SetBranchAddress("jetGenPhi", &treeLeaf.jetGenPhi, &b_jetGenPhi);
   fChain->SetBranchAddress("jetGenPartonMomID", &treeLeaf.jetGenPartonMomID, &b_jetGenPartonMomID);
  }
  fChain->SetBranchAddress("nAK8Jet", &treeLeaf.nAK8Jet, &b_nAK8Jet);
  fChain->SetBranchAddress("AK8JetPt", &treeLeaf.AK8JetPt, &b_AK8JetPt);
  fChain->SetBranchAddress("AK8JetEn", &treeLeaf.AK8JetEn, &b_AK8JetEn);
  fChain->SetBranchAddress("AK8JetRawPt", &treeLeaf.AK8JetRawPt, &b_AK8JetRawPt);
  fChain->SetBranchAddress("AK8JetRawEn", &treeLeaf.AK8JetRawEn, &b_AK8JetRawEn);
  fChain->SetBranchAddress("AK8JetEta", &treeLeaf.AK8JetEta, &b_AK8JetEta);
  fChain->SetBranchAddress("AK8JetPhi", &treeLeaf.AK8JetPhi, &b_AK8JetPhi);
  fChain->SetBranchAddress("AK8JetMass", &treeLeaf.AK8JetMass, &b_AK8JetMass);
  fChain->SetBranchAddress("AK8Jet_tau1", &treeLeaf.AK8Jet_tau1, &b_AK8Jet_tau1);
  fChain->SetBranchAddress("AK8Jet_tau2", &treeLeaf.AK8Jet_tau2, &b_AK8Jet_tau2);
  fChain->SetBranchAddress("AK8Jet_tau3", &treeLeaf.AK8Jet_tau3, &b_AK8Jet_tau3);
  fChain->SetBranchAddress("AK8JetCHF", &treeLeaf.AK8JetCHF, &b_AK8JetCHF);
  fChain->SetBranchAddress("AK8JetNHF", &treeLeaf.AK8JetNHF, &b_AK8JetNHF);
  fChain->SetBranchAddress("AK8JetCEF", &treeLeaf.AK8JetCEF, &b_AK8JetCEF);
  fChain->SetBranchAddress("AK8JetNEF", &treeLeaf.AK8JetNEF, &b_AK8JetNEF);
  fChain->SetBranchAddress("AK8JetNCH", &treeLeaf.AK8JetNCH, &b_AK8JetNCH);
  fChain->SetBranchAddress("AK8Jetnconstituents", &treeLeaf.AK8Jetnconstituents, &b_AK8Jetnconstituents);
  fChain->SetBranchAddress("AK8JetPFLooseId", &treeLeaf.AK8JetPFLooseId, &b_AK8JetPFLooseId);
  fChain->SetBranchAddress("AK8CHSSoftDropJetMass", &treeLeaf.AK8CHSSoftDropJetMass, &b_AK8CHSSoftDropJetMass);
  fChain->SetBranchAddress("AK8JetpfBoostedDSVBTag", &treeLeaf.AK8JetpfBoostedDSVBTag, &b_AK8JetpfBoostedDSVBTag);
  fChain->SetBranchAddress("AK8JetJECUnc", &treeLeaf.AK8JetJECUnc, &b_AK8JetJECUnc);
  if (isMC){
   fChain->SetBranchAddress("AK8JetPartonID", &treeLeaf.AK8JetPartonID, &b_AK8JetPartonID);
   fChain->SetBranchAddress("AK8JetGenJetIndex", &treeLeaf.AK8JetGenJetIndex, &b_AK8JetGenJetIndex);
   fChain->SetBranchAddress("AK8JetGenJetEn", &treeLeaf.AK8JetGenJetEn, &b_AK8JetGenJetEn);
   fChain->SetBranchAddress("AK8JetGenJetPt", &treeLeaf.AK8JetGenJetPt, &b_AK8JetGenJetPt);
   fChain->SetBranchAddress("AK8JetGenJetEta", &treeLeaf.AK8JetGenJetEta, &b_AK8JetGenJetEta);
   fChain->SetBranchAddress("AK8JetGenJetPhi", &treeLeaf.AK8JetGenJetPhi, &b_AK8JetGenJetPhi);
   fChain->SetBranchAddress("AK8JetGenPartonID", &treeLeaf.AK8JetGenPartonID, &b_AK8JetGenPartonID);
   fChain->SetBranchAddress("AK8JetGenEn", &treeLeaf.AK8JetGenEn, &b_AK8JetGenEn);
   fChain->SetBranchAddress("AK8JetGenPt", &treeLeaf.AK8JetGenPt, &b_AK8JetGenPt);
   fChain->SetBranchAddress("AK8JetGenEta", &treeLeaf.AK8JetGenEta, &b_AK8JetGenEta);
   fChain->SetBranchAddress("AK8JetGenPhi", &treeLeaf.AK8JetGenPhi, &b_AK8JetGenPhi);
   fChain->SetBranchAddress("AK8JetGenPartonMomID", &treeLeaf.AK8JetGenPartonMomID, &b_AK8JetGenPartonMomID);
  }
  fChain->SetBranchAddress("nAK8softdropSubjet", &treeLeaf.nAK8softdropSubjet, &b_nAK8softdropSubjet);
  fChain->SetBranchAddress("AK8softdropSubjetPt", &treeLeaf.AK8softdropSubjetPt, &b_AK8softdropSubjetPt);
  fChain->SetBranchAddress("AK8softdropSubjetEta", &treeLeaf.AK8softdropSubjetEta, &b_AK8softdropSubjetEta);
  fChain->SetBranchAddress("AK8softdropSubjetPhi", &treeLeaf.AK8softdropSubjetPhi, &b_AK8softdropSubjetPhi);
  fChain->SetBranchAddress("AK8softdropSubjetMass", &treeLeaf.AK8softdropSubjetMass, &b_AK8softdropSubjetMass);
  fChain->SetBranchAddress("AK8softdropSubjetE", &treeLeaf.AK8softdropSubjetE, &b_AK8softdropSubjetE);
  fChain->SetBranchAddress("AK8softdropSubjetCharge", &treeLeaf.AK8softdropSubjetCharge, &b_AK8softdropSubjetCharge);
  fChain->SetBranchAddress("AK8softdropSubjetFlavour", &treeLeaf.AK8softdropSubjetFlavour, &b_AK8softdropSubjetFlavour);
  fChain->SetBranchAddress("AK8softdropSubjetCSV", &treeLeaf.AK8softdropSubjetCSV, &b_AK8softdropSubjetCSV);
}

void TInputOutputTree::InitOutput(TTree* outputTree,bool isMC)
{
  gROOT->ProcessLine("#include <vector>");
  //global event (keep all, as general rule)
  outputTree->Branch("run",                  &treeLeaf.run,        "run/I");
  outputTree->Branch("event",                &treeLeaf.event,      "event/L");
  outputTree->Branch("lumis",                &treeLeaf.lumis,      "lumis/I");
  outputTree->Branch("isData",               &treeLeaf.isData,     "isData/O");
  outputTree->Branch("nVtx",                 &treeLeaf.nVtx,       "nVtx/I");
  outputTree->Branch("nTrksPV",              &treeLeaf.nTrksPV,    "nVtxPV/I");
  outputTree->Branch("vtx",                  &treeLeaf.vtx,        "vtx/F"); 
  outputTree->Branch("vty",                  &treeLeaf.vty,        "vty/F"); 
  outputTree->Branch("vtz",                  &treeLeaf.vtz,        "vtz/F"); 
  outputTree->Branch("rho",                  &treeLeaf.rho,        "rho/F");
  outputTree->Branch("rhoCentral",           &treeLeaf.rhoCentral, "rhoCentral/F");
  outputTree->Branch("HLTEleMuX",            &treeLeaf.HLTEleMuX, "HLTEleMuX/l");
  outputTree->Branch("HLTPho",               &treeLeaf.HLTPho, "HLTPho/l");
  outputTree->Branch("HLTJet",               &treeLeaf.HLTJet, "HLTJet/l");
  outputTree->Branch("HLTEleMuXIsPrescaled", &treeLeaf.HLTEleMuXIsPrescaled, "HLTEleMuXIsPrescaled/l");
  outputTree->Branch("HLTPhoIsPrescaled",    &treeLeaf.HLTPhoIsPrescaled, "HLTPhoIsPrescaled/l");
  outputTree->Branch("HLTJetIsPrescaled",    &treeLeaf.HLTJetIsPrescaled, "HLTJetIsPrescaled/l");
  if(isMC){
    outputTree->Branch("pdf",&treeLeaf.pdf);
    outputTree->Branch("pthat",&treeLeaf.pthat, "pthat/F");
    outputTree->Branch("processID",&treeLeaf.processID, "processID/F");
    outputTree->Branch("genWeight",&treeLeaf.genWeight, "genWeight/F");
    outputTree->Branch("genHT",&treeLeaf.genHT, "genHT/F");

    outputTree->Branch("nPUInfo",&treeLeaf.nPUInfo, "nPUInfo/I");
    outputTree->Branch("nPU",&treeLeaf.nPU);
    outputTree->Branch("puBX",&treeLeaf.puBX);
    outputTree->Branch("puTrue",&treeLeaf.puTrue);

    outputTree->Branch("nMC",         &treeLeaf.nMC, "nMC/I");
    outputTree->Branch("mcPID",       &treeLeaf.mcPID);
    outputTree->Branch("mcVtx",	   &treeLeaf.mcVtx);	    
    outputTree->Branch("mcVty",	   &treeLeaf.mcVty);	    
    outputTree->Branch("mcVtz",	   &treeLeaf.mcVtz);	    
    outputTree->Branch("mcPt",	   &treeLeaf.mcPt);	    
    outputTree->Branch("mcMass",	   &treeLeaf.mcMass);	    
    outputTree->Branch("mcEta",	   &treeLeaf.mcEta);	    
    outputTree->Branch("mcPhi",	   &treeLeaf.mcPhi);	    
    outputTree->Branch("mcE",	   &treeLeaf.mcE);	    
    outputTree->Branch("mcEt",	   &treeLeaf.mcEt);	    
    outputTree->Branch("mcGMomPID",  &treeLeaf.mcGMomPID);    
    outputTree->Branch("mcMomPID",   &treeLeaf.mcMomPID);     
    outputTree->Branch("mcMomPt",	   &treeLeaf.mcMomPt);		    
    outputTree->Branch("mcMomMass",  &treeLeaf.mcMomMass);    
    outputTree->Branch("mcMomEta",   &treeLeaf.mcMomEta);     
    outputTree->Branch("mcMomPhi",   &treeLeaf.mcMomPhi);     
    outputTree->Branch("mcIndex",	   &treeLeaf.mcIndex);		    
    outputTree->Branch("mcStatusFlag",&treeLeaf.mcStatusFlag);
    outputTree->Branch("mcParentage",&treeLeaf.mcParentage);
    outputTree->Branch("mcStatus",   &treeLeaf.mcStatus);
    outputTree->Branch("mcCalIsoDR03",&treeLeaf.mcCalIsoDR03);
    outputTree->Branch("mcTrkIsoDR03",&treeLeaf.mcTrkIsoDR03);
    outputTree->Branch("mcCalIsoDR04",&treeLeaf.mcCalIsoDR04);
    outputTree->Branch("mcTrkIsoDR04",&treeLeaf.mcTrkIsoDR04);
    outputTree->Branch("genMET",&treeLeaf.genMET,"genMET/F");
    outputTree->Branch("genMETPhi",&treeLeaf.genMETPhi,"genMETPhi/F");
  }
  //met (minimal stuff)
  outputTree->Branch("metFilters",&treeLeaf.metFilters,"metFilters/I");
  outputTree->Branch("pfMET",&treeLeaf.pfMET,"pfMET/F");
  outputTree->Branch("pfMETPhi",&treeLeaf.pfMETPhi,"pfMETPhi/F");
  outputTree->Branch("pfMETsumEt",&treeLeaf.pfMETsumEt,"pfMETsumEt/F");
  outputTree->Branch("pfMETmEtSig",&treeLeaf.pfMETmEtSig,"pfMETmEtSig");
  outputTree->Branch("pfMETSig",&treeLeaf.pfMETSig,"pfMETSig");
  // (local) variables associated with tree branches
  //photon
  outputTree->Branch("nPho"		  ,&treeLeaf.nPho, "nPho/I");		     
  outputTree->Branch("phoE"		  ,&treeLeaf.phoE      	);		     
  outputTree->Branch("phoEt"      ,&treeLeaf.phoEt   ); 
  outputTree->Branch("phoEta"		  ,&treeLeaf.phoEta	 );		     
  outputTree->Branch("phoPhi"		  ,&treeLeaf.phoPhi	 );		     
  outputTree->Branch("phoSCE"		  ,&treeLeaf.phoSCE	);		      
  outputTree->Branch("phoSCRawE"		  ,&treeLeaf.phoSCRawE	);		      
  outputTree->Branch("phoESEn",&treeLeaf.phoESEn);
  outputTree->Branch("phoESEnP1",&treeLeaf.phoESEnP1);
  outputTree->Branch("phoESEnP2",&treeLeaf.phoESEnP2);
  outputTree->Branch("phoSCEta"		  ,&treeLeaf.phoSCEta		   );		      
  outputTree->Branch("phoSCPhi"		  ,&treeLeaf.phoSCPhi		   );		      
  outputTree->Branch("phoSCEtaWidth"	  ,&treeLeaf.phoSCEtaWidth	   );	      
  outputTree->Branch("phoSCPhiWidth"	  ,&treeLeaf.phoSCPhiWidth	   );	      
  outputTree->Branch("phoSCBrem"		  ,&treeLeaf.phoSCBrem	   );		      
  outputTree->Branch("phohasPixelSeed"	  ,&treeLeaf.phohasPixelSeed	  );	      
  outputTree->Branch("phoEleVeto"		  ,&treeLeaf.phoEleVeto	);		      
  outputTree->Branch("phoR9"		  ,&treeLeaf.phoR9		   );		      
  outputTree->Branch("phoHoverE"		  ,&treeLeaf.phoHoverE	);		      
  outputTree->Branch("phoSigmaIEtaIEta"	  ,&treeLeaf.phoSigmaIEtaIEta);	      
  outputTree->Branch("phoSigmaIEtaIPhi"	  ,&treeLeaf.phoSigmaIEtaIPhi);	      
  outputTree->Branch("phoSigmaIPhiIPhi"	  ,&treeLeaf.phoSigmaIPhiIPhi);	      
  outputTree->Branch("phoE1x3",&treeLeaf.phoE1x3);
  outputTree->Branch("phoE2x2",&treeLeaf.phoE2x2);
  outputTree->Branch("phoE2x5Max",&treeLeaf.phoE2x5Max);
  outputTree->Branch("phoE5x5",&treeLeaf.phoE5x5);
  outputTree->Branch("phoESEffSigmaRR"	  ,&treeLeaf.phoESEffSigmaRR	   );	      
  outputTree->Branch("phoSigmaIEtaIEtaFull5x5",&treeLeaf.phoSigmaIEtaIEtaFull5x5 );   
  outputTree->Branch("phoSigmaIEtaIPhiFull5x5",&treeLeaf.phoSigmaIEtaIPhiFull5x5 );   
  outputTree->Branch("phoSigmaIPhiIPhiFull5x5",&treeLeaf.phoSigmaIPhiIPhiFull5x5 );   
  outputTree->Branch("phoE1x3Full5x5",&treeLeaf.phoE1x3Full5x5);
  outputTree->Branch("phoE2x2Full5x5",&treeLeaf.phoE2x2Full5x5);
  outputTree->Branch("phoE2x5MaxFull5x5",&treeLeaf.phoE2x5MaxFull5x5);
  outputTree->Branch("phoE5x5Full5x5",&treeLeaf.phoE5x5Full5x5);
  outputTree->Branch("phoR9Full5x5",&treeLeaf.phoR9Full5x5);
  outputTree->Branch("phoSeedBCE",&treeLeaf.phoSeedBCE);
  outputTree->Branch("phoSeedBCEta",&treeLeaf.phoSeedBCEta);
  outputTree->Branch("phoPFChIso"		  ,&treeLeaf.phoPFChIso		 );		      
  outputTree->Branch("phoPFPhoIso"	  ,&treeLeaf.phoPFPhoIso		 );	              
  outputTree->Branch("phoPFNeuIso"	  ,&treeLeaf.phoPFNeuIso		 );	              
  outputTree->Branch("phoPFChWorstIso"		  ,&treeLeaf.phoPFChWorstIso		 );		      
  outputTree->Branch("phoPFChIsoFrix1",&treeLeaf.phoPFChIsoFrix1);
  outputTree->Branch("phoPFChIsoFrix2",&treeLeaf.phoPFChIsoFrix2);
  outputTree->Branch("phoPFChIsoFrix3",&treeLeaf.phoPFChIsoFrix3);
  outputTree->Branch("phoPFChIsoFrix4",&treeLeaf.phoPFChIsoFrix4);
  outputTree->Branch("phoPFChIsoFrix5",&treeLeaf.phoPFChIsoFrix5);
  outputTree->Branch("phoPFChIsoFrix6",&treeLeaf.phoPFChIsoFrix6);
  outputTree->Branch("phoPFChIsoFrix7",&treeLeaf.phoPFChIsoFrix7);
  outputTree->Branch("phoPFChIsoFrix8",&treeLeaf.phoPFChIsoFrix8);
  outputTree->Branch("phoPFPhoIsoFrix1",&treeLeaf.phoPFPhoIsoFrix1);
  outputTree->Branch("phoPFPhoIsoFrix2",&treeLeaf.phoPFPhoIsoFrix2);
  outputTree->Branch("phoPFPhoIsoFrix3",&treeLeaf.phoPFPhoIsoFrix3);
  outputTree->Branch("phoPFPhoIsoFrix4",&treeLeaf.phoPFPhoIsoFrix4);
  outputTree->Branch("phoPFPhoIsoFrix5",&treeLeaf.phoPFPhoIsoFrix5);
  outputTree->Branch("phoPFPhoIsoFrix6",&treeLeaf.phoPFPhoIsoFrix6);
  outputTree->Branch("phoPFPhoIsoFrix7",&treeLeaf.phoPFPhoIsoFrix7);
  outputTree->Branch("phoPFPhoIsoFrix8",&treeLeaf.phoPFPhoIsoFrix8);
  outputTree->Branch("phoPFNeuIsoFrix1",&treeLeaf.phoPFNeuIsoFrix1);
  outputTree->Branch("phoPFNeuIsoFrix2",&treeLeaf.phoPFNeuIsoFrix2);
  outputTree->Branch("phoPFNeuIsoFrix3",&treeLeaf.phoPFNeuIsoFrix3);
  outputTree->Branch("phoPFNeuIsoFrix4",&treeLeaf.phoPFNeuIsoFrix4);
  outputTree->Branch("phoPFNeuIsoFrix5",&treeLeaf.phoPFNeuIsoFrix5);
  outputTree->Branch("phoPFNeuIsoFrix6",&treeLeaf.phoPFNeuIsoFrix6);
  outputTree->Branch("phoPFNeuIsoFrix7",&treeLeaf.phoPFNeuIsoFrix7);
  outputTree->Branch("phoPFNeuIsoFrix8",&treeLeaf.phoPFNeuIsoFrix8);
  outputTree->Branch("phoEcalRecHitSumEtConeDR03",&treeLeaf.phoEcalRecHitSumEtConeDR03);
  outputTree->Branch("phohcalDepth1TowerSumEtConeDR03",&treeLeaf.phohcalDepth1TowerSumEtConeDR03);
  outputTree->Branch("phohcalDepth2TowerSumEtConeDR03",&treeLeaf.phohcalDepth2TowerSumEtConeDR03);
  outputTree->Branch("phohcalTowerSumEtConeDR03",&treeLeaf.phohcalTowerSumEtConeDR03);
  outputTree->Branch("photrkSumPtHollowConeDR03",&treeLeaf.photrkSumPtHollowConeDR03);
  outputTree->Branch("phoIDMVA"             ,&treeLeaf.phoIDMVA              );    
  outputTree->Branch("phoFiredSingleTrgs"	  ,&treeLeaf.phoFiredSingleTrgs	 );	      
  outputTree->Branch("phoFiredDoubleTrgs"	  ,&treeLeaf.phoFiredDoubleTrgs	 );  
  outputTree->Branch("phoIDbit"             ,&treeLeaf.phoIDbit              );    
  // electrons
  outputTree->Branch("nEle",                    &treeLeaf.nEle,                    "nEle/I");
  outputTree->Branch("eleCharge",               &treeLeaf.eleCharge);
  outputTree->Branch("eleChargeConsistent",     &treeLeaf.eleChargeConsistent);
  outputTree->Branch("eleEn",                   &treeLeaf.eleEn);
  outputTree->Branch("eleSCEn",                 &treeLeaf.eleSCEn);
  // outputTree->Branch("eleESEn",                 &treeLeaf.eleESEn);
  // outputTree->Branch("eleESEnP1",               &treeLeaf.eleESEnP1);
  // outputTree->Branch("eleESEnP2",               &treeLeaf.eleESEnP2);
  outputTree->Branch("eleD0",                   &treeLeaf.eleD0);
  outputTree->Branch("eleDz",                   &treeLeaf.eleDz);
  outputTree->Branch("elePt",                   &treeLeaf.elePt);
  outputTree->Branch("eleEta",                  &treeLeaf.eleEta);
  outputTree->Branch("elePhi",                  &treeLeaf.elePhi);
  outputTree->Branch("eleR9",                   &treeLeaf.eleR9);
  outputTree->Branch("eleSCEta",                &treeLeaf.eleSCEta);
  outputTree->Branch("eleSCPhi",                &treeLeaf.eleSCPhi);
  outputTree->Branch("eleSCRawEn",              &treeLeaf.eleSCRawEn);
  // outputTree->Branch("eleSCEtaWidth",           &treeLeaf.eleSCEtaWidth);
  // outputTree->Branch("eleSCPhiWidth",           &treeLeaf.eleSCPhiWidth);
  outputTree->Branch("eleHoverE",               &treeLeaf.eleHoverE);
  outputTree->Branch("eleEoverP",               &treeLeaf.eleEoverP);
  // outputTree->Branch("eleEoverPout",            &treeLeaf.eleEoverPout);
  // outputTree->Branch("eleEoverPInv",            &treeLeaf.eleEoverPInv);
  outputTree->Branch("eleBrem",                 &treeLeaf.eleBrem);
  outputTree->Branch("eledEtaAtVtx",            &treeLeaf.eledEtaAtVtx);
  outputTree->Branch("eledPhiAtVtx",            &treeLeaf.eledPhiAtVtx);
  // outputTree->Branch("eledEtaAtCalo",           &treeLeaf.eledEtaAtCalo);
  outputTree->Branch("eleSigmaIEtaIEta",        &treeLeaf.eleSigmaIEtaIEta);
  outputTree->Branch("eleSigmaIEtaIPhi",        &treeLeaf.eleSigmaIEtaIPhi);
  outputTree->Branch("eleSigmaIPhiIPhi",        &treeLeaf.eleSigmaIPhiIPhi);
  outputTree->Branch("eleSigmaIEtaIEtaFull5x5", &treeLeaf.eleSigmaIEtaIEtaFull5x5);
  outputTree->Branch("eleSigmaIPhiIPhiFull5x5", &treeLeaf.eleSigmaIPhiIPhiFull5x5);
  outputTree->Branch("eleConvVeto",             &treeLeaf.eleConvVeto);
  outputTree->Branch("eleMissHits",             &treeLeaf.eleMissHits);
  outputTree->Branch("eleESEffSigmaRR",         &treeLeaf.eleESEffSigmaRR);
  outputTree->Branch("elePFChIso",              &treeLeaf.elePFChIso);
  outputTree->Branch("elePFPhoIso",             &treeLeaf.elePFPhoIso);
  outputTree->Branch("elePFNeuIso",             &treeLeaf.elePFNeuIso);
  outputTree->Branch("elePFPUIso",              &treeLeaf.elePFPUIso);
  //outputTree->Branch("elePFClusEcalIso",        &treeLeaf.elePFClusEcalIso);
  //outputTree->Branch("elePFClusHcalIso",        &treeLeaf.elePFClusHcalIso);
  outputTree->Branch("eleIDMVANonTrg",          &treeLeaf.eleIDMVANonTrg);
  outputTree->Branch("eleIDMVATrg",             &treeLeaf.eleIDMVATrg);
  // outputTree->Branch("eledEtaseedAtVtx",        &treeLeaf.eledEtaseedAtVtx);
  // outputTree->Branch("eleE1x5",                 &treeLeaf.eleE1x5);
  // outputTree->Branch("eleE2x5",                 &treeLeaf.eleE2x5);
  // outputTree->Branch("eleE5x5",                 &treeLeaf.eleE5x5);
  // outputTree->Branch("eleE1x5Full5x5",          &treeLeaf.eleE1x5Full5x5);
  // outputTree->Branch("eleE2x5Full5x5",          &treeLeaf.eleE2x5Full5x5);
  // outputTree->Branch("eleE5x5Full5x5",          &treeLeaf.eleE5x5Full5x5);
  // outputTree->Branch("eleR9Full5x5",                &treeLeaf.eleR9Full5x5);
  // outputTree->Branch("eleEcalDrivenSeed",           &treeLeaf.eleEcalDrivenSeed);
  // outputTree->Branch("eleDr03EcalRecHitSumEt",      &treeLeaf.eleDr03EcalRecHitSumEt);
  // outputTree->Branch("eleDr03HcalDepth1TowerSumEt", &treeLeaf.eleDr03HcalDepth1TowerSumEt);
  // outputTree->Branch("eleDr03HcalDepth2TowerSumEt", &treeLeaf.eleDr03HcalDepth2TowerSumEt);
  // outputTree->Branch("eleDr03HcalTowerSumEt",       &treeLeaf.eleDr03HcalTowerSumEt);
  outputTree->Branch("eleDr03TkSumPt",              &treeLeaf.eleDr03TkSumPt);
  // outputTree->Branch("elecaloEnergy",               &treeLeaf.elecaloEnergy);
  // outputTree->Branch("eleTrkdxy",                   &treeLeaf.eleTrkdxy);
  // outputTree->Branch("eleKFHits",                   &treeLeaf.eleKFHits);
  // outputTree->Branch("eleKFChi2",                   &treeLeaf.eleKFChi2);
  // outputTree->Branch("eleGSFPt",                    &treeLeaf.eleGSFPt);
  // outputTree->Branch("eleGSFEta",                   &treeLeaf.eleGSFEta);
  // outputTree->Branch("eleGSFPhi",                   &treeLeaf.eleGSFPhi);
  // outputTree->Branch("eleGSFCharge",                &treeLeaf.eleGSFCharge);
  // outputTree->Branch("eleGSFHits",                  &treeLeaf.eleGSFHits);
  // outputTree->Branch("eleGSFMissHits",              &treeLeaf.eleGSFMissHits);
  // outputTree->Branch("eleGSFNHitsMax",              &treeLeaf.eleGSFNHitsMax);
  // outputTree->Branch("eleGSFVtxProb",               &treeLeaf.eleGSFVtxProb);
  // outputTree->Branch("eleGSFlxyPV",                 &treeLeaf.eleGSFlxyPV);
  // outputTree->Branch("eleGSFlxyBS",                 &treeLeaf.eleGSFlxyBS);
  // outputTree->Branch("eleBCEn",                     &treeLeaf.eleBCEn);
  // outputTree->Branch("eleBCEta",                    &treeLeaf.eleBCEta);
  // outputTree->Branch("eleBCPhi",                    &treeLeaf.eleBCPhi);
  // outputTree->Branch("eleBCS25",                    &treeLeaf.eleBCS25);
  // outputTree->Branch("eleBCS15",                    &treeLeaf.eleBCS15);
  // outputTree->Branch("eleBCSieie",                  &treeLeaf.eleBCSieie);
  // outputTree->Branch("eleBCSieip",                  &treeLeaf.eleBCSieip);
  // outputTree->Branch("eleBCSipip",                  &treeLeaf.eleBCSipip);
  outputTree->Branch("eleFiredTrgs",                &treeLeaf.eleFiredTrgs);
  //  if (runeleIDVID)
  outputTree->Branch("eleIDbit",  &treeLeaf.eleIDbit);
  //devel only
  // outputTree->Branch("eleESEnP1Raw",              &treeLeaf.eleESEnP1Raw);
  // outputTree->Branch("eleESEnP2Raw",              &treeLeaf.eleESEnP2Raw);
  // outputTree->Branch("eleESEnEta",                &treeLeaf.eleESEnEta);
  // outputTree->Branch("eleESEnPhi",                &treeLeaf.eleESEnPhi);
  // outputTree->Branch("eleESEnZ",                  &treeLeaf.eleESEnZ);
  // outputTree->Branch("eleESEnP",                  &treeLeaf.eleESEnP);
  // outputTree->Branch("eleESEnX",                  &treeLeaf.eleESEnX);
  // outputTree->Branch("eleESEnY",                  &treeLeaf.eleESEnY);
  // outputTree->Branch("eleESEnS",                  &treeLeaf.eleESEnS);
  // outputTree->Branch("eleESEnE",                  &treeLeaf.eleESEnE);
  // outputTree->Branch("nGSFTrk",                   &treeLeaf.nGSFTrk);
  // outputTree->Branch("gsfPt",                     &treeLeaf.gsfPt);
  // outputTree->Branch("gsfEta",                    &treeLeaf.gsfEta);
  // outputTree->Branch("gsfPhi",                    &treeLeaf.gsfPhi);
  //muons
  outputTree->Branch("nMu",&treeLeaf.nMu,"nMu/I");
  outputTree->Branch("muPt",&treeLeaf.muPt);	     
  outputTree->Branch("muEn",&treeLeaf.muEn);	     
  outputTree->Branch("muEta",&treeLeaf.muEta);	     
  outputTree->Branch("muPhi",&treeLeaf.muPhi);	     
  outputTree->Branch("muCharge",&treeLeaf.muCharge);   
  outputTree->Branch("muType",&treeLeaf.muType   );	     
  outputTree->Branch("muIsLooseID",&treeLeaf.muIsLooseID); 
  outputTree->Branch("muIsMediumID",&treeLeaf.muIsMediumID);
  outputTree->Branch("muIsTightID",&treeLeaf.muIsTightID);
  outputTree->Branch("muIsSoftID",&treeLeaf.muIsSoftID);
  outputTree->Branch("muIsHighPtID",&treeLeaf.muIsHighPtID);
  outputTree->Branch("muD0",&treeLeaf.muD0	   );	     
  outputTree->Branch("muDz",&treeLeaf.muDz	   );	     
  outputTree->Branch("muChi2NDF",&treeLeaf.muChi2NDF );   
  outputTree->Branch("muTrkLayers",&treeLeaf.muTrkLayers); 
  outputTree->Branch("muPixelHits",&treeLeaf.muPixelHits); 
  outputTree->Branch("muStations",&treeLeaf.muStations);  
  outputTree->Branch("muPFChIso",&treeLeaf.muPFChIso );   
  outputTree->Branch("muPFPhoIso",&treeLeaf.muPFPhoIso);  
  outputTree->Branch("muPFNeuIso",&treeLeaf.muPFNeuIso); 
  outputTree->Branch("muPFPUIso",&treeLeaf.muPFPUIso );   
  outputTree->Branch("muFiredTrgs",&treeLeaf.muFiredTrgs);

  //jets (minimal stuff)
  outputTree->Branch("nJet",&treeLeaf.nJet, "nJet/I");
  outputTree->Branch("jetPt",&treeLeaf.jetPt);
  outputTree->Branch("jetEn",&treeLeaf.jetEn);
  outputTree->Branch("jetEta",&treeLeaf.jetEta);
  outputTree->Branch("jetPhi",	     &treeLeaf.jetPhi);
  outputTree->Branch("jetRawPt",	     &treeLeaf.jetRawPt);	          
  outputTree->Branch("jetRawEn",	     &treeLeaf.jetRawEn); 
  outputTree->Branch("jetArea",&treeLeaf.jetArea);
  outputTree->Branch("jetpfCombinedInclusiveSecondaryVertexV2BJetTags",&treeLeaf.jetpfCombinedInclusiveSecondaryVertexV2BJetTags);
  outputTree->Branch("jetJetProbabilityBJetTags",&treeLeaf.jetJetProbabilityBJetTags);
  outputTree->Branch("jetpfCombinedMVABJetTags",&treeLeaf.jetpfCombinedMVABJetTags);
  outputTree->Branch("jetPFLooseId",&treeLeaf.jetPFLooseId);
  outputTree->Branch("jetPUidFullDiscriminant",&treeLeaf.jetPUidFullDiscriminant);
  outputTree->Branch("jetJECUnc",	     &treeLeaf.jetJECUnc);	           
  outputTree->Branch("jetFiredTrgs",    &treeLeaf.jetFiredTrgs);    
  outputTree->Branch("jetCHF",&treeLeaf.jetCHF);
  outputTree->Branch("jetNHF",&treeLeaf.jetNHF);
  outputTree->Branch("jetCEF",&treeLeaf.jetCEF);
  outputTree->Branch("jetNEF",&treeLeaf.jetNEF);
  outputTree->Branch("jetNCH",&treeLeaf.jetNCH);
  outputTree->Branch("jetHFHAE",&treeLeaf.jetHFHAE);
  outputTree->Branch("jetHFEME",&treeLeaf.jetHFEME);
  outputTree->Branch("jetNConstituents",&treeLeaf.jetNConstituents);
  if(isMC){
    outputTree->Branch("jetPartonID",  &treeLeaf.jetPartonID);  
    outputTree->Branch("jetGenJetIndex",  &treeLeaf.jetGenJetIndex);  
    outputTree->Branch("jetGenJetEn",     &treeLeaf.jetGenJetEn);     
    outputTree->Branch("jetGenJetPt",     &treeLeaf.jetGenJetPt);     
    outputTree->Branch("jetGenJetEta",    &treeLeaf.jetGenJetEta);    
    outputTree->Branch("jetGenJetPhi",    &treeLeaf.jetGenJetPhi);    
    outputTree->Branch("jetGenPartonID",  &treeLeaf.jetGenPartonID);  
    outputTree->Branch("jetGenEn",	     &treeLeaf.jetGenEn);            
    outputTree->Branch("jetGenPt",	     &treeLeaf.jetGenPt);            
    outputTree->Branch("jetGenEta",	     &treeLeaf.jetGenEta);           
    outputTree->Branch("jetGenPhi",	     &treeLeaf.jetGenPhi);           
    outputTree->Branch("jetGenPartonMomID",&treeLeaf.jetGenPartonMomID);
  }
  outputTree->Branch("nAK8Jet",&treeLeaf.nAK8Jet, "nAK8Jet/I");
  outputTree->Branch("AK8JetPt",&treeLeaf.AK8JetPt);
  outputTree->Branch("AK8JetEn",&treeLeaf.AK8JetEn);
  outputTree->Branch("AK8JetRawPt",&treeLeaf.AK8JetRawPt);
  outputTree->Branch("AK8JetRawEn",&treeLeaf.AK8JetRawEn);
  outputTree->Branch("AK8JetEta",&treeLeaf.AK8JetEta);
  outputTree->Branch("AK8JetPhi",&treeLeaf.AK8JetPhi);
  outputTree->Branch("AK8JetMass",&treeLeaf.AK8JetMass);
  outputTree->Branch("AK8Jet_tau1",&treeLeaf.AK8Jet_tau1);
  outputTree->Branch("AK8Jet_tau2",&treeLeaf.AK8Jet_tau2);
  outputTree->Branch("AK8Jet_tau3",&treeLeaf.AK8Jet_tau3);
  outputTree->Branch("AK8JetCHF",&treeLeaf.AK8JetCHF);
  outputTree->Branch("AK8JetNHF",&treeLeaf.AK8JetNHF);
  outputTree->Branch("AK8JetCEF",&treeLeaf.AK8JetCEF);
  outputTree->Branch("AK8JetNEF",&treeLeaf.AK8JetNEF);
  outputTree->Branch("AK8JetNCH",&treeLeaf.AK8JetNCH);
  outputTree->Branch("AK8Jetnconstituents",&treeLeaf.AK8Jetnconstituents);
  outputTree->Branch("AK8JetPFLooseId",&treeLeaf.AK8JetPFLooseId);
  outputTree->Branch("AK8CHSSoftDropJetMass",&treeLeaf.AK8CHSSoftDropJetMass);
  outputTree->Branch("AK8JetpfBoostedDSVBTag",&treeLeaf.AK8JetpfBoostedDSVBTag);
  outputTree->Branch("AK8JetJECUnc",&treeLeaf.AK8JetJECUnc);
  if(isMC){
    outputTree->Branch("AK8JetPartonID",  &treeLeaf.AK8JetPartonID);  
    outputTree->Branch("AK8JetGenJetIndex",  &treeLeaf.AK8JetGenJetIndex);  
    outputTree->Branch("AK8JetGenJetEn",     &treeLeaf.AK8JetGenJetEn);     
    outputTree->Branch("AK8JetGenJetPt",     &treeLeaf.AK8JetGenJetPt);     
    outputTree->Branch("AK8JetGenJetEta",    &treeLeaf.AK8JetGenJetEta);    
    outputTree->Branch("AK8JetGenJetPhi",    &treeLeaf.AK8JetGenJetPhi);    
    outputTree->Branch("AK8JetGenPartonID",  &treeLeaf.AK8JetGenPartonID);  
    outputTree->Branch("AK8JetGenEn",	     &treeLeaf.AK8JetGenEn);            
    outputTree->Branch("AK8JetGenPt",	     &treeLeaf.AK8JetGenPt);            
    outputTree->Branch("AK8JetGenEta",	     &treeLeaf.AK8JetGenEta);           
    outputTree->Branch("AK8JetGenPhi",	     &treeLeaf.AK8JetGenPhi);           
    outputTree->Branch("AK8JetGenPartonMomID",&treeLeaf.AK8JetGenPartonMomID);
  }
  outputTree->Branch("nAK8softdropSubjet",&treeLeaf.nAK8softdropSubjet);
  outputTree->Branch("AK8softdropSubjetPt",&treeLeaf.AK8softdropSubjetPt);
  outputTree->Branch("AK8softdropSubjetEta",&treeLeaf.AK8softdropSubjetEta);
  outputTree->Branch("AK8softdropSubjetPhi",&treeLeaf.AK8softdropSubjetPhi);
  outputTree->Branch("AK8softdropSubjetMass",&treeLeaf.AK8softdropSubjetMass);
  outputTree->Branch("AK8softdropSubjetE",&treeLeaf.AK8softdropSubjetE);
  outputTree->Branch("AK8softdropSubjetCharge",&treeLeaf.AK8softdropSubjetCharge);
  outputTree->Branch("AK8softdropSubjetFlavour",&treeLeaf.AK8softdropSubjetFlavour);
  outputTree->Branch("AK8softdropSubjetCSV",&treeLeaf.AK8softdropSubjetCSV);
        
  //  outputTree->Branch("eeMass"      ,&outLeaf.eeMass);
  // outputTree->Branch("eegMass"     ,&outLeaf.eegMass);
  // outputTree->Branch("gammaEt"     ,&outLeaf.gammaEt);
  // outputTree->Branch("deltaR"     ,&outLeaf.deltaR);
}
