#include "plotter_skimmed.h"
#include "TString.h"
#include <TH1F.h>
#include <iostream>
#include <THStack.h>
#include "tdrstyle.C"
using namespace std;

void plotter_skimmed(){
  setTDRStyle();
  std::string fdata = "skimmed_data_histos.root";
  std::string fbkg = "skimmed_mc_histos.root";
  std::string fsignal = "mc_signal_histos.root";
  //std::string fdata = "skimmed_data_histos_phoLMT.root";
  //std::string fbkg = "skimmed_mc_histos_phoLMT_4fb.root";
  //std::string fsignal = "mc_signal_histos_phoLMT_4fb.root";
  //std::string fdata = "skimmed_data_histos_dSVB_L.root";
  //std::string fbkg = "skimmed_mc_histos_dSVB_L_4fb.root";
  //std::string fsignal = "mc_signal_histos_dSVB_L_4fb.root";
  //std::string fdata = "skimmed_data_histos_dSVB_M.root";
  //std::string fbkg = "skimmed_mc_histos_dSVB_M_4fb.root";
  //std::string fsignal = "mc_signal_histos_dSVB_M_4fb.root";
  //std::string fdata = "skimmed_data_histos_dSVB_T.root";
  //std::string fbkg = "skimmed_mc_histos_dSVB_T_4fb.root";
  //std::string fsignal = "mc_signal_histos_dSVB_T_4fb.root";
  //std::string fdata = "skimmed_data_histos_met_bL.root";
  //std::string fbkg = "skimmed_mc_histos_met_bL_4fb.root";
  //std::string fsignal = "mc_signal_histos_met_bL_4fb.root";
  //std::string fdata = "skimmed_data_histos_met_bL_higgs.root";
  //std::string fbkg = "skimmed_mc_histos_met_bL_higgs_4fb.root";
  //std::string fsignal = "mc_signal_histos_met_bL_higgs_4fb.root";
  
  //std::string fbkg = "skimmed_mc_histos_phoLMT.root";
  //std::string fsignal = "mc_signal_histos_phoLMT.root";
  //std::string fsignal = "mc_signal_histos_dSVB_T.root";
  //std::string fbkg = "skimmed_mc_histos_dSVB_T.root";

  TH1D *hdata_nPU = getplot(fdata,"pileup");
  TH1D *hdata_cuts = getplot(fdata,"hdata_cuts");
  TH1D *hdata_nVtx = getplot(fdata,"hdata_nVtx");
  TH1D *hdata_phoEtL = getplot(fdata,"hdata_phoEtL");
  TH1D *hdata_phoEtM = getplot(fdata,"hdata_phoEtM");
  TH1D *hdata_phoEtT = getplot(fdata,"hdata_phoEtT");
  TH1D *hdata_phoEtaL = getplot(fdata,"hdata_phoEtaL");
  TH1D *hdata_phoEtaM = getplot(fdata,"hdata_phoEtaM");
  TH1D *hdata_phoEtaT = getplot(fdata,"hdata_phoEtaT");
  TH1D *hdata_pfMET = getplot(fdata,"hdata_pfMET");
  TH1D *hdata_nPho = getplot(fdata,"hdata_nPho");
  TH1D *hdata_nEle = getplot(fdata,"hdata_nEle");
  TH1D *hdata_nEleM = getplot(fdata,"hdata_nEleM");
  TH1D *hdata_nEleT = getplot(fdata,"hdata_nEleT");
  TH1D *hdata_nMu = getplot(fdata,"hdata_nMu");
  TH1D *hdata_nMuM = getplot(fdata,"hdata_nMuM");
  TH1D *hdata_nMuT = getplot(fdata,"hdata_nMuT");
  TH1D *hdata_nTrksPV = getplot(fdata,"hdata_nTrksPV");
  TH1D *hdata_njets= getplot(fdata,"hdata_njets");
  TH1D *hdata_CSVbjetsL = getplot(fdata,"hdata_CSVbjetsL");
  TH1D *hdata_CSVbjetsM = getplot(fdata,"hdata_CSVbjetsM");
  TH1D *hdata_CSVbjetsT = getplot(fdata,"hdata_CSVbjetsT");
  TH1D *hdata_cMVAbjetsL = getplot(fdata,"hdata_cMVAbjetsL");
  TH1D *hdata_cMVAbjetsM = getplot(fdata,"hdata_cMVAbjetsM");
  TH1D *hdata_cMVAbjetsT = getplot(fdata,"hdata_cMVAbjetsT");
  TH1D *hdata_BDSVbjetsL = getplot(fdata,"hdata_BDSVbjetsL");
  TH1D *hdata_BDSVbjetsM = getplot(fdata,"hdata_BDSVbjetsM");
  TH1D *hdata_BDSVbjetsT = getplot(fdata,"hdata_BDSVbjetsT");
  TH1D *hdata_doubleB= getplot(fdata,"hdata_doubleB");
  TH1D *hdata_doubleB_highdB= getplot(fdata,"hdata_doubleB_highdB");
  TH1D *hdata_bjetCSV= getplot(fdata,"hdata_bjetCSV");
  TH1D *hdata_bjetCSV2= getplot(fdata,"hdata_bjetCSV2");
  TH1D *hdata_bjetcMVA = getplot(fdata,"hdata_bjetcMVA");
  TH1D *hdata_bjetcMVA2 = getplot(fdata,"hdata_bjetcMVA2");
  TH1D *hdata_jetpt = getplot(fdata,"hdata_jetpt");
  TH1D *hdata_AK8jetpt = getplot(fdata,"hdata_AK8jetpt");
  TH1D *hdata_AK8ljetmass = getplot(fdata,"hdata_AK8ljetmass");
  TH1D *hdata_AK8bjetpt = getplot(fdata,"hdata_AK8bjetpt");
  TH1D *hdata_AK8bjetmass = getplot(fdata,"hdata_AK8bjetmass");
  TH1D *hdata_AK8bPrunedjetmass = getplot(fdata,"hdata_AK8bPrunedjetmass");
  TH1D *hdata_AK8bPrunedCorrjetmass = getplot(fdata,"hdata_AK8bPrunedCorrjetmass");
  TH1D *hdata_AK8jetmass = getplot(fdata,"hdata_AK8jetmass");
  TH1D *hdata_dRphoAK8jet= getplot(fdata,"hdata_dRphoAK8jet");
  TH1D *hdata_nAK8jets = getplot(fdata,"hdata_nAK8jets");
  TH1D *hdata_HT_before = getplot(fdata,"hdata_HT_before");
  TH1D *hdata_EMHT_before = getplot(fdata,"hdata_EMHT_before");
  TH1D *hdata_HT_after = getplot(fdata,"hdata_HT_after");
  TH1D *hdata_EMHT_after = getplot(fdata,"hdata_EMHT_after");
  TH1D *hdata_AK8HT_before = getplot(fdata,"hdata_AK8HT_before");
  TH1D *hdata_AK8EMHT_before = getplot(fdata,"hdata_AK8EMHT_before");
  TH1D *hdata_AK8HT_after = getplot(fdata,"hdata_AK8HT_after");
  TH1D *hdata_AK8EMHT_after = getplot(fdata,"hdata_AK8EMHT_after");

  THStack *sbkg_nVtx = new THStack("sbkg_nVtx","");
  THStack *sbkg_nPU = new THStack("sbkg_nPU","");
  THStack *sbkg_cuts = new THStack("sbkg_cuts","");

  THStack *sbkg_phoEtL = new THStack("sbkg_phoEtL","");
  THStack *sbkg_phoEtM = new THStack("sbkg_phoEtM","");
  THStack *sbkg_phoEtT = new THStack("sbkg_phoEtT","");
  THStack *sbkg_phoEtaL = new THStack("sbkg_phoEtaL","");
  THStack *sbkg_phoEtaM = new THStack("sbkg_phoEtaM","");
  THStack *sbkg_phoEtaT = new THStack("sbkg_phoEtaT","");
  THStack *sbkg_pfMET = new THStack("sbkg_pfMET","");
  THStack *sbkg_nPho = new THStack("sbkg_nPho","");
  THStack *sbkg_nTrksPV = new THStack("sbkg_nTrksPV","");
  THStack *sbkg_nEle = new THStack("sbkg_nEle","");
  THStack *sbkg_nEleM = new THStack("sbkg_nEleM","");
  THStack *sbkg_nEleT = new THStack("sbkg_nEleT","");
  THStack *sbkg_nMu = new THStack("sbkg_nMu","");
  THStack *sbkg_nMuM = new THStack("sbkg_nMuM","");
  THStack *sbkg_nMuT = new THStack("sbkg_nMuT","");
  
  THStack *sbkg_njets = new THStack("sbkg_njets","");
  THStack *sbkg_CSVbjetsL = new THStack("sbkg_CSVbjetsL","");
  THStack *sbkg_CSVbjetsM = new THStack("sbkg_CSVbjetsM","");
  THStack *sbkg_CSVbjetsT = new THStack("sbkg_CSVbjetsT","");
  THStack *sbkg_cMVAbjetsL = new THStack("sbkg_cMVAbjetsL","");
  THStack *sbkg_cMVAbjetsM = new THStack("sbkg_cMVAbjetsM","");
  THStack *sbkg_cMVAbjetsT = new THStack("sbkg_cMVAbjetsT","");
  THStack *sbkg_BDSVbjetsL = new THStack("sbkg_BDSVbjetsL","");
  THStack *sbkg_BDSVbjetsM = new THStack("sbkg_BDSVbjetsM","");
  THStack *sbkg_BDSVbjetsT = new THStack("sbkg_BDSVbjetsT","");
  THStack *sbkg_jetpt = new THStack("sbkg_jetpt","");
  THStack *sbkg_nAK8jets = new THStack("sbkg_nAK8jets","");
  THStack *sbkg_AK8jetpt = new THStack("sbkg_AK8jetpt","");
  THStack *sbkg_AK8bjetpt = new THStack("sbkg_AK8bjetpt","");
  THStack *sbkg_AK8ljetmass = new THStack("sbkg_AK8ljetmass","");
  THStack *sbkg_AK8bjetmass = new THStack("sbkg_AK8bjetmass","");
  THStack *sbkg_AK8bPrunedjetmass = new THStack("sbkg_AK8bPrunedjetmass","");
  THStack *sbkg_AK8bPrunedCorrjetmass = new THStack("sbkg_AK8bPrunedCorrjetmass","");
  THStack *sbkg_AK8jetmass = new THStack("sbkg_AK8jetmass","");
  
  THStack *sbkg_dRphoAK8jet = new THStack("sbkg_dRphoAK8jet","");

  THStack *sbkg_doubleB = new THStack("sbkg_doubleB","");
  THStack *sbkg_doubleB_highdB = new THStack("sbkg_doubleB_highdB","");
  THStack *sbkg_bjetCSV = new THStack("sbkg_bjetCSV","");
  THStack *sbkg_bjetCSV2 = new THStack("sbkg_bjetCSV2","");
  THStack *sbkg_bjetcMVA = new THStack("sbkg_bjetcMVA","");
  THStack *sbkg_bjetcMVA2 = new THStack("sbkg_bjetcMVA2","");

  THStack *sbkg_HT_before = new THStack("sbkg_HT_before","");
  THStack *sbkg_EMHT_before = new THStack("sbkg_EMHT_before","");
  THStack *sbkg_HT_after = new THStack("sbkg_HT_after","");
  THStack *sbkg_EMHT_after = new THStack("sbkg_EMHT_after","");

  THStack *sbkg_AK8HT_before = new THStack("sbkg_AK8HT_before","");
  THStack *sbkg_AK8EMHT_before = new THStack("sbkg_AK8EMHT_before","");
  THStack *sbkg_AK8HT_after = new THStack("sbkg_AK8HT_after","");
  THStack *sbkg_AK8EMHT_after = new THStack("sbkg_AK8EMHT_after","");

  addallMC(sbkg_cuts, fbkg, "hbkg_cuts");
  addallMC(sbkg_nVtx, fbkg, "hbkg_nVtx");
  addallMC(sbkg_nPU, fbkg, "hbkg_nPU");
  addallMC(sbkg_phoEtL, fbkg, "hbkg_phoEtL");
  addallMC(sbkg_phoEtM, fbkg, "hbkg_phoEtM");
  addallMC(sbkg_phoEtT, fbkg, "hbkg_phoEtT");
  addallMC(sbkg_phoEtaL, fbkg, "hbkg_phoEtaL");
  addallMC(sbkg_phoEtaM, fbkg, "hbkg_phoEtaM");
  addallMC(sbkg_phoEtaT, fbkg, "hbkg_phoEtaT");
  addallMC(sbkg_pfMET, fbkg, "hbkg_pfMET");
  addallMC(sbkg_nPho, fbkg, "hbkg_nPho");
  addallMC(sbkg_nTrksPV, fbkg, "hbkg_nTrksPV");
  addallMC(sbkg_nEle, fbkg, "hbkg_nEle");
  addallMC(sbkg_nEleM, fbkg, "hbkg_nEleM");
  addallMC(sbkg_nEleT, fbkg, "hbkg_nEleT");
  addallMC(sbkg_nMu, fbkg, "hbkg_nMu");
  addallMC(sbkg_nMuM, fbkg, "hbkg_nMuM");
  addallMC(sbkg_nMuT, fbkg, "hbkg_nMuT");
  addallMC(sbkg_njets, fbkg, "hbkg_njets");
  addallMC(sbkg_jetpt, fbkg, "hbkg_jetpt");
  addallMC(sbkg_CSVbjetsL, fbkg, "hbkg_CSVbjetsL");
  addallMC(sbkg_CSVbjetsM, fbkg, "hbkg_CSVbjetsM");
  addallMC(sbkg_CSVbjetsT, fbkg, "hbkg_CSVbjetsT");
  addallMC(sbkg_cMVAbjetsL, fbkg, "hbkg_cMVAbjetsL");
  addallMC(sbkg_cMVAbjetsM, fbkg, "hbkg_cMVAbjetsM");
  addallMC(sbkg_cMVAbjetsT, fbkg, "hbkg_cMVAbjetsT");
  addallMC(sbkg_BDSVbjetsL, fbkg, "hbkg_BDSVbjetsL");
  addallMC(sbkg_BDSVbjetsM, fbkg, "hbkg_BDSVbjetsM");
  addallMC(sbkg_BDSVbjetsT, fbkg, "hbkg_BDSVbjetsT");
  addallMC(sbkg_nAK8jets, fbkg, "hbkg_nAK8jets");
  addallMC(sbkg_AK8bjetpt, fbkg, "hbkg_AK8bjetpt");
  addallMC(sbkg_AK8ljetmass, fbkg, "hbkg_AK8ljetmass");
  addallMC(sbkg_AK8bjetmass, fbkg, "hbkg_AK8bjetmass");
  addallMC(sbkg_AK8bPrunedjetmass, fbkg, "hbkg_AK8bPrunedjetmass");
  addallMC(sbkg_AK8bPrunedCorrjetmass, fbkg, "hbkg_AK8bPrunedCorrjetmass");
  addallMC(sbkg_AK8jetmass, fbkg, "hbkg_AK8jetmass");
  addallMC(sbkg_dRphoAK8jet, fbkg, "hbkg_dRphoAK8jet");
  addallMC(sbkg_doubleB, fbkg, "hbkg_doubleB");
  addallMC(sbkg_doubleB_highdB, fbkg, "hbkg_doubleB_highdB");
  addallMC(sbkg_bjetCSV, fbkg, "hbkg_bjetCSV");
  addallMC(sbkg_bjetCSV2, fbkg, "hbkg_bjetCSV2");
  addallMC(sbkg_bjetcMVA, fbkg, "hbkg_bjetcMVA");
  addallMC(sbkg_bjetcMVA2, fbkg, "hbkg_bjetcMVA2");
  addallMC(sbkg_HT_before, fbkg, "hbkg_HT_before");
  addallMC(sbkg_EMHT_before, fbkg, "hbkg_EMHT_before");
  addallMC(sbkg_HT_after, fbkg, "hbkg_HT_after");
  addallMC(sbkg_EMHT_after, fbkg, "hbkg_EMHT_after");
  addallMC(sbkg_AK8HT_before, fbkg, "hbkg_AK8HT_before");
  addallMC(sbkg_AK8EMHT_before, fbkg, "hbkg_AK8EMHT_before");
  addallMC(sbkg_AK8HT_after, fbkg, "hbkg_AK8HT_after");
  addallMC(sbkg_AK8EMHT_after, fbkg, "hbkg_AK8EMHT_after");

//signal
  nsignal=3;
  TH1D *h_PUweight[nsignal];
  TH1D *hsignal_nVtx[nsignal];
  TH1D *hsignal_nPU[nsignal];
  TH1D *hsignal_cuts[nsignal];
  TH1D *hsignal_phoEtL[nsignal];
  TH1D *hsignal_phoEtM[nsignal];
  TH1D *hsignal_phoEtT[nsignal];
  TH1D *hsignal_phoEtaL[nsignal];
  TH1D *hsignal_phoEtaM[nsignal];
  TH1D *hsignal_phoEtaT[nsignal];
  TH1D *hsignal_pfMET[nsignal];
  TH1D *hsignal_nPho[nsignal];
  TH1D *hsignal_nTrksPV[nsignal];
  TH1D *hsignal_nEle[nsignal];
  TH1D *hsignal_nEleM[nsignal];
  TH1D *hsignal_nEleT[nsignal];
  TH1D *hsignal_nMu[nsignal];
  TH1D *hsignal_nMuM[nsignal];
  TH1D *hsignal_nMuT[nsignal];
  TH1D *hsignal_njets[nsignal];
  TH1D *hsignal_CSVbjetsL[nsignal];
  TH1D *hsignal_CSVbjetsM[nsignal];
  TH1D *hsignal_CSVbjetsT[nsignal];
  TH1D *hsignal_cMVAbjetsL[nsignal];
  TH1D *hsignal_cMVAbjetsM[nsignal];
  TH1D *hsignal_cMVAbjetsT[nsignal];
  TH1D *hsignal_BDSVbjetsL[nsignal];
  TH1D *hsignal_BDSVbjetsM[nsignal];
  TH1D *hsignal_BDSVbjetsT[nsignal];
  TH1D *hsignal_jetpt[nsignal];
  TH1D *hsignal_nAK8jets[nsignal];
  TH1D *hsignal_AK8bjetpt[nsignal];
  TH1D *hsignal_AK8ljetmass[nsignal];
  TH1D *hsignal_AK8bjetmass[nsignal];
  TH1D *hsignal_AK8bPrunedjetmass[nsignal];
  TH1D *hsignal_AK8bPrunedCorrjetmass[nsignal];
  TH1D *hsignal_AK8jetmass[nsignal];
  TH1D *hsignal_dRphoAK8jet[nsignal];
  TH1D *hsignal_doubleB[nsignal];
  TH1D *hsignal_doubleB_highdB[nsignal];
  TH1D *hsignal_bjetCSV[nsignal];
  TH1D *hsignal_bjetCSV2[nsignal];
  TH1D *hsignal_bjetcMVA[nsignal];
  TH1D *hsignal_bjetcMVA2[nsignal];
  TH1D *hsignal_HT_before[nsignal];
  TH1D *hsignal_EMHT_before[nsignal];
  TH1D *hsignal_HT_after[nsignal];
  TH1D *hsignal_EMHT_after[nsignal];
  TH1D *hsignal_AK8HT_before[nsignal];
  TH1D *hsignal_AK8EMHT_before[nsignal];
  TH1D *hsignal_AK8HT_after[nsignal];
  TH1D *hsignal_AK8EMHT_after[nsignal];
  //mc truth histograms
  TH1D *hsignal_Hjetpt[nsignal];
  TH1D *hsignal_AK8Hjetpt[nsignal];
  TH1D *hsignal_AK8Hjetmass[nsignal];
  TH1D *hsignal_AK8HPrunedjetmass[nsignal];
  TH1D *hsignal_AK8HPrunedCorrjetmass[nsignal];
  TH1D *hsignal_dRphoH[nsignal];
  TH1D *hsignal_dRTphoH[nsignal];
  TH2D *hsignal_AK8ptHpt[nsignal];
  TH2D *hsignal_AK8massHpt[nsignal];
  TH1D *hsignal_Hpt[nsignal];
  for (Int_t i=0;i<nsignal;i++){
    hsignal_cuts[i] = getplot(fsignal,Form("hsignal_cuts[%i]",i));
    hsignal_nVtx[i] = getplot(fsignal,Form("hsignal_nVtx[%i]",i));
    hsignal_nPU[i] = getplot(fsignal,Form("hsignal_nPU[%i]",i));
    
    hsignal_phoEtL[i] = getplot(fsignal,Form("hsignal_phoEtL[%i]",i));
    hsignal_phoEtM[i] = getplot(fsignal,Form("hsignal_phoEtM[%i]",i));
    hsignal_phoEtT[i] = getplot(fsignal,Form("hsignal_phoEtT[%i]",i));
    hsignal_phoEtaL[i]= getplot(fsignal,Form("hsignal_phoEtaL[%i]",i));
    hsignal_phoEtaM[i]= getplot(fsignal,Form("hsignal_phoEtaM[%i]",i));
    hsignal_phoEtaT[i]= getplot(fsignal,Form("hsignal_phoEtaT[%i]",i));
    hsignal_pfMET[i]= getplot(fsignal,Form("hsignal_pfMET[%i]",i));
    hsignal_nPho[i]= getplot(fsignal,Form("hsignal_nPho[%i]",i));
    hsignal_nTrksPV[i]= getplot(fsignal,Form("hsignal_nTrksPV[%i]",i));
    hsignal_nEle[i]= getplot(fsignal,Form("hsignal_nEle[%i]",i));
    hsignal_nEleM[i]= getplot(fsignal,Form("hsignal_nEleM[%i]",i));
    hsignal_nEleT[i]= getplot(fsignal,Form("hsignal_nEleT[%i]",i));
    hsignal_nMu[i]= getplot(fsignal,Form("hsignal_nMu[%i]",i));
    hsignal_nMuM[i]= getplot(fsignal,Form("hsignal_nMuM[%i]",i));
    hsignal_nMuT[i]= getplot(fsignal,Form("hsignal_nMuT[%i]",i));
    
    hsignal_njets[i] = getplot(fsignal,Form("hsignal_njets[%i]",i));
    hsignal_CSVbjetsL[i] = getplot(fsignal,Form("hsignal_CSVbjetsL[%i]",i));
    hsignal_CSVbjetsM[i] = getplot(fsignal,Form("hsignal_CSVbjetsM[%i]",i));
    hsignal_CSVbjetsT[i] = getplot(fsignal,Form("hsignal_CSVbjetsT[%i]",i));
    hsignal_cMVAbjetsL[i] = getplot(fsignal,Form("hsignal_cMVAbjetsL[%i]",i));
    hsignal_cMVAbjetsM[i] = getplot(fsignal,Form("hsignal_cMVAbjetsM[%i]",i));
    hsignal_cMVAbjetsT[i] = getplot(fsignal,Form("hsignal_cMVAbjetsT[%i]",i));
    hsignal_BDSVbjetsL[i] = getplot(fsignal,Form("hsignal_BDSVbjetsL[%i]",i));
    hsignal_BDSVbjetsM[i] = getplot(fsignal,Form("hsignal_BDSVbjetsM[%i]",i));
    hsignal_BDSVbjetsT[i] = getplot(fsignal,Form("hsignal_BDSVbjetsT[%i]",i));
    hsignal_jetpt[i] = getplot(fsignal,Form("hsignal_jetpt[%i]",i));
    hsignal_nAK8jets[i] = getplot(fsignal,Form("hsignal_nAK8jets[%i]",i));
    hsignal_AK8bjetpt[i] = getplot(fsignal,Form("hsignal_AK8bjetpt[%i]",i));
    hsignal_AK8ljetmass[i] = getplot(fsignal,Form("hsignal_AK8ljetmass[%i]",i));
    hsignal_AK8bjetmass[i] = getplot(fsignal,Form("hsignal_AK8bjetmass[%i]",i));
    hsignal_AK8bPrunedjetmass[i] = getplot(fsignal,Form("hsignal_AK8bPrunedjetmass[%i]",i));
    hsignal_AK8bPrunedCorrjetmass[i] = getplot(fsignal,Form("hsignal_AK8bPrunedCorrjetmass[%i]",i));
    hsignal_AK8jetmass[i] = getplot(fsignal,Form("hsignal_AK8jetmass[%i]",i));
   
    hsignal_dRphoAK8jet[i]= getplot(fsignal,Form("hsignal_dRphoAK8jet[%i]",i));
  
    hsignal_doubleB[i] = getplot(fsignal,Form("hsignal_doubleB[%i]",i));
    hsignal_doubleB_highdB[i] = getplot(fsignal,Form("hsignal_doubleB_highdB[%i]",i));
    hsignal_bjetCSV[i]= getplot(fsignal,Form("hsignal_bjetCSV[%i]",i));
    hsignal_bjetCSV2[i]= getplot(fsignal,Form("hsignal_bjetCSV2[%i]",i));
    hsignal_bjetcMVA[i] = getplot(fsignal,Form("hsignal_bjetcMVA[%i]",i));
    hsignal_bjetcMVA2[i] = getplot(fsignal,Form("hsignal_bjetcMVA2[%i]",i));
 
    hsignal_HT_before[i] = getplot(fsignal,Form("hsignal_HT_before[%i]",i));
    hsignal_EMHT_before[i] = getplot(fsignal,Form("hsignal_EMHT_before[%i]",i));
    hsignal_HT_after[i] = getplot(fsignal,Form("hsignal_HT_after[%i]",i));
    hsignal_EMHT_after[i] = getplot(fsignal,Form("hsignal_EMHT_after[%i]",i));
    
    hsignal_AK8HT_before[i] = getplot(fsignal,Form("hsignal_AK8HT_before[%i]",i));
    hsignal_AK8EMHT_before[i] = getplot(fsignal,Form("hsignal_AK8EMHT_before[%i]",i));
    hsignal_AK8HT_after[i] = getplot(fsignal,Form("hsignal_AK8HT_after[%i]",i));
    hsignal_AK8EMHT_after[i] = getplot(fsignal,Form("hsignal_AK8EMHT_after[%i]",i));

    //truth histograms
    hsignal_Hjetpt[i] = getplot(fsignal,Form("hsignal_Hjetpt[%i]",i));
    hsignal_AK8Hjetpt[i] = getplot(fsignal,Form("hsignal_AK8Hjetpt[%i]",i));
    hsignal_AK8Hjetmass[i] = getplot(fsignal,Form("hsignal_AK8Hjetmass[%i]",i));
    hsignal_AK8HPrunedjetmass[i] = getplot(fsignal,Form("hsignal_AK8HPrunedjetmass[%i]",i));
    hsignal_AK8HPrunedCorrjetmass[i] = getplot(fsignal,Form("hsignal_AK8HPrunedCorrjetmass[%i]",i));
    
    hsignal_dRphoH[i]= getplot(fsignal,Form("hsignal_dRphoH[%i]",i));
    hsignal_dRTphoH[i]= getplot(fsignal,Form("hsignal_dRTphoH[%i]",i));
    
    hsignal_AK8ptHpt[i]= getplot2d(fsignal,Form("hsignal_AK8ptHpt[%i]",i));
    hsignal_AK8massHpt[i]= getplot2d(fsignal,Form("hsignal_AK8massHpt[%i]",i));
   
    hsignal_Hpt[i] = getplot(fsignal,Form("hsignal_Hpt[%i]",i));
  }

  TLegend *leg = new TLegend(0.55,0.45,0.9,0.85,"");

  TCanvas *c1 = new TCanvas("c1", "c1",1200,600);
  //gStyle->SetOptStat(0);
  c1->Divide(3,1);
  c1->cd(1);
  gPad->SetLogy();
  sbkg_cuts->Print("all");
  hdata_cuts->Print("all");
  hsignal_cuts[0]->Print("all");
  hsignal_cuts[1]->Print("all");
  //hdata_cuts->SetMinimum(10);
  drawthings(nsignal, fsignal, hdata_cuts, sbkg_cuts, "hsignal_cuts");
  //leg->AddEntry("hdata_cuts",   "Data", "P");
  leg->AddEntry("hbkg_cuts[0]",   "#gammaJet", "f");
  leg->AddEntry("hbkg_cuts[1]",   "WJetsToL#nu", "f");
  leg->AddEntry("hbkg_cuts[2]",   "Z#gammaJet", "f");
  leg->AddEntry("hbkg_cuts[3]",   "Multijet", "f");
  leg->AddEntry("hbkg_cuts[10]",   "ZJetsTo#nu#nu", "f");
  leg->AddEntry("hbkg_cuts[14]",   "TT#gammaJets", "f");
  leg->AddEntry("hbkg_cuts[15]",   "ZJetsToQQ", "f");
  leg->AddEntry("hbkg_cuts[16]",   "W#gammaJets", "f");
  leg->AddEntry("hbkg_cuts[17]",   "TTJets", "f");
  leg->AddEntry("hsignal_cuts[0]","m_{#Chi^{#pm}_{1}}=400 m_{#Chi^{0}_{1}}=200", "pl");
  leg->AddEntry("hsignal_cuts[2]","m_{#Chi^{#pm}_{1}}=600 m_{#Chi^{0}_{1}}=200", "pl");
  leg->AddEntry("hsignal_cuts[1]","m_{g}=1000 m_{#Chi^{0}_{1}}=200", "pl");
  leg->Draw("same");
  c1->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nVtx, sbkg_nVtx, "hsignal_nVtx");
  leg->Draw("same");
  c1->cd(3);
  //gPad->SetLogy();
  hdata_pfMET->SetMinimum(1);
  drawthings(nsignal, fsignal, hdata_pfMET, sbkg_pfMET, "hsignal_pfMET");
  leg->Draw("same");
  
  //TCanvas *ctest = new TCanvas("ctest", "ctest",1200,600);
  //gPad->SetLogy();
  //drawthings(nsignal, fsignal, hdata_nPho, sbkg_nPho, "hsignal_nPho");
  //leg->Draw("same");
/*
  TCanvas *c2 = new TCanvas("c2", "c2",1200,600);
  c2->Divide(3,1);
  c2->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nPho, sbkg_nPho, "hsignal_nPho");
  leg->Draw("same");
  c2->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_phoEtL, sbkg_phoEtL, "hsignal_phoEtL");
  leg->Draw("same");
  c2->cd(3);
  gPad->SetLogy();
  //hdata_phoEta->SetMinimum(10);
  drawthings(nsignal, fsignal, hdata_phoEtaL, sbkg_phoEtaL, "hsignal_phoEtaL");
  leg->Draw("same");

  TCanvas *c3 = new TCanvas("c3", "c3",1200,600);
  c3->Divide(3,1);
  c3->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nEle, sbkg_nEle, "hsignal_nEle");
  leg->Draw("same");
  c3->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nMu, sbkg_nMu, "hsignal_nMu");
  leg->Draw("same");
  c3->cd(3);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_njets, sbkg_njets, "hsignal_njets");
  leg->Draw("same");
*/
  TCanvas *cut = new TCanvas("cut", "cut",1200,1200);
  cut->Divide(2,2);
  cut->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_cuts, sbkg_cuts, "hsignal_cuts");
  leg->Draw("same");
  cut->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_HT_after, sbkg_HT_after, "hsignal_HT_after");
  leg->Draw("same");
  cut->cd(3);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_EMHT_after, sbkg_EMHT_after, "hsignal_EMHT_after");
  leg->Draw("same");
  cut->cd(4);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_pfMET, sbkg_pfMET, "hsignal_pfMET");
  leg->Draw("same");

  TCanvas *c5 = new TCanvas("c5", "c5",1200,600);
  c5->Divide(3,1);
  c5->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_HT_after, sbkg_HT_after, "hsignal_HT_after");
  leg->Draw("same");
  c5->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_EMHT_after, sbkg_EMHT_after, "hsignal_EMHT_after");
  leg->Draw("same");
  c5->cd(3);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_pfMET, sbkg_pfMET, "hsignal_pfMET");
  leg->Draw("same");
  
  TCanvas *c4 = new TCanvas("c4", "c4",1200,600);
  c4->Divide(3,1);
  c4->cd(1);
  gPad->SetLogy();
  //hdata_doubleB_highdB->SetMinimum(1);
  drawthings(nsignal, fsignal, hdata_doubleB_highdB, sbkg_doubleB_highdB, "hsignal_doubleB_highdB");
  leg->Draw("same");
  c4->cd(2);
  drawthings(nsignal, fsignal, hdata_AK8bjetpt, sbkg_AK8bjetpt, "hsignal_AK8bjetpt");
  gPad->SetLogy();
  leg->Draw("same");
  c4->cd(3);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_AK8bPrunedCorrjetmass, sbkg_AK8bPrunedCorrjetmass, "hsignal_AK8bPrunedCorrjetmass");
  leg->Draw("same");

/*  
  TCanvas *cx = new TCanvas("cx", "cx",1200,600);
  cx->Divide(3,1);
  cx->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_AK8bjetmass, sbkg_AK8bjetmass, "hsignal_AK8bjetmass");
  leg->Draw("same");
  cx->cd(2);
  drawthings(nsignal, fsignal, hdata_AK8bPrunedjetmass, sbkg_AK8bPrunedjetmass, "hsignal_AK8bPrunedjetmass");
  leg->Draw("same");
  cx->cd(3);
  drawthings(nsignal, fsignal, hdata_AK8bPrunedCorrjetmass, sbkg_AK8bPrunedCorrjetmass, "hsignal_AK8bPrunedCorrjetmass");
  leg->Draw("same");
*/  
  TCanvas *cx2 = new TCanvas("cx2", "cx2",1200,600);
  cx2->Divide(3,1);
  cx2->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_phoEtL, sbkg_phoEtL, "hsignal_phoEtL");
  MCintegral(nsignal, fsignal, sbkg_phoEtL, "hsignal_phoEtL", 0, 0);
  leg->Draw("same");
  cx2->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_phoEtM, sbkg_phoEtM, "hsignal_phoEtM");
  MCintegral(nsignal, fsignal, sbkg_phoEtM, "hsignal_phoEtM", 0, 0);
  leg->Draw("same");
  cx2->cd(3);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_phoEtT, sbkg_phoEtT, "hsignal_phoEtT");
  MCintegral(nsignal, fsignal, sbkg_phoEtT, "hsignal_phoEtT", 0, 0);
  leg->Draw("same");
  
  TCanvas *c_bjets = new TCanvas("c_bjets", "c_bjets",1200,1200);
  c_bjets->Divide(3,2);
  c_bjets->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_BDSVbjetsL, sbkg_BDSVbjetsL, "hsignal_BDSVbjetsL");
  MCintegral(nsignal, fsignal, sbkg_BDSVbjetsL, "hsignal_BDSVbjetsL", 2, 10);
  leg->Draw("same");
  c_bjets->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_BDSVbjetsM, sbkg_BDSVbjetsM, "hsignal_BDSVbjetsM");
  MCintegral(nsignal, fsignal, sbkg_BDSVbjetsM, "hsignal_BDSVbjetsM", 2, 10);
  leg->Draw("same");
  c_bjets->cd(3);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_BDSVbjetsT, sbkg_BDSVbjetsT, "hsignal_BDSVbjetsT");
  MCintegral(nsignal, fsignal, sbkg_BDSVbjetsT, "hsignal_BDSVbjetsT", 2, 10);
  leg->Draw("same");
  c_bjets->cd(4);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_CSVbjetsL, sbkg_CSVbjetsL, "hsignal_CSVbjetsL");
  MCintegral(nsignal, fsignal, sbkg_CSVbjetsL, "hsignal_CSVbjetsL", 3, 10);
  leg->Draw("same");
  c_bjets->cd(5);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_CSVbjetsM, sbkg_CSVbjetsM, "hsignal_CSVbjetsM");
  MCintegral(nsignal, fsignal, sbkg_CSVbjetsM, "hsignal_CSVbjetsM", 3, 10);
  leg->Draw("same");
  c_bjets->cd(6);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_CSVbjetsT, sbkg_CSVbjetsT, "hsignal_CSVbjetsT");
  MCintegral(nsignal, fsignal, sbkg_CSVbjetsT, "hsignal_CSVbjetsT", 3, 10);
  leg->Draw("same");
/*
  TCanvas *M3xx = new TCanvas("M3xx", "M3xx",1200,600);
  M3xx->Divide(3,1);
  M3xx->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nEle, sbkg_nEle, "hsignal_nEle");
  leg->Draw("same");
  M3xx->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nEleM, sbkg_nEleM, "hsignal_nEleM");
  leg->Draw("same");
  M3xx->cd(3);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nEleT, sbkg_nEleT, "hsignal_nEleT");
  leg->Draw("same");
  
  
  TCanvas *M3x = new TCanvas("M3x", "M3x",1200,600);
  M3x->Divide(3,1);
  M3x->cd(1);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nMu, sbkg_nMu, "hsignal_nMu");
  leg->Draw("same");
  M3x->cd(2);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nMuM, sbkg_nMuT, "hsignal_nMuM");
  leg->Draw("same");
  M3x->cd(3);
  gPad->SetLogy();
  drawthings(nsignal, fsignal, hdata_nMuM, sbkg_nMuT, "hsignal_nMuT");
  leg->Draw("same");
*/  
  TCanvas *cphoEtL = new TCanvas("cphoEtL", "cphoEtL");
  cphoEtL->cd();
  gPad->SetLogy();
  hdata_phoEtL->GetYaxis()->SetTitle("Events / 33.3 GeV");
  hdata_phoEtL->GetYaxis()->SetTitleOffset(1.15);
  hdata_phoEtL->GetXaxis()->SetTitle("E_{T}^{#gamma}  [GeV]");
  hdata_phoEtL->GetXaxis()->CenterTitle(kTRUE);
  hdata_phoEtL->GetXaxis()->SetTitleOffset(1.15);
  drawthings(nsignal, fsignal, hdata_phoEtL, sbkg_phoEtL, "hsignal_phoEtL");
  leg->Draw("same");
}
